# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul3/ui/MainNoHD.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Refrensi = QtWidgets.QPushButton(self.centralwidget)
        self.Refrensi.setGeometry(QtCore.QRect(50, 240, 120, 120))
        self.Refrensi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Refrensi.setMouseTracking(True)
        self.Refrensi.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Refrensi.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.Refrensi.setText("")
        self.Refrensi.setObjectName("Refrensi")
        self.Controller = QtWidgets.QPushButton(self.centralwidget)
        self.Controller.setGeometry(QtCore.QRect(410, 220, 250, 143))
        self.Controller.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Controller.setMouseTracking(True)
        self.Controller.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/PID.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.Controller.setText("")
        self.Controller.setObjectName("Controller")
        self.Plant = QtWidgets.QPushButton(self.centralwidget)
        self.Plant.setGeometry(QtCore.QRect(750, 230, 250, 143))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Plant.setFont(font)
        self.Plant.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Plant.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Plant.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.Plant.setText("")
        self.Plant.setObjectName("Plant")
        self.scopeOutput = QtWidgets.QPushButton(self.centralwidget)
        self.scopeOutput.setGeometry(QtCore.QRect(1140, 250, 79, 100))
        self.scopeOutput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scopeOutput.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Scope.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.scopeOutput.setText("")
        self.scopeOutput.setObjectName("scopeOutput")
        self.scopeController = QtWidgets.QPushButton(self.centralwidget)
        self.scopeController.setGeometry(QtCore.QRect(1140, 140, 79, 100))
        self.scopeController.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scopeController.setMouseTracking(True)
        self.scopeController.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Scope.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.scopeController.setText("")
        self.scopeController.setObjectName("scopeController")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.frame.setStyleSheet("border-image: url(:/Main/Background Baru.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.runSim = QtWidgets.QPushButton(self.frame)
        self.runSim.setGeometry(QtCore.QRect(640, 550, 601, 71))
        self.runSim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.runSim.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Run Sim Button.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.runSim.setText("")
        self.runSim.setObjectName("runSim")
        self.Submit = QtWidgets.QPushButton(self.frame)
        self.Submit.setGeometry(QtCore.QRect(20, 550, 601, 71))
        self.Submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Submit.setStyleSheet("QPushButton {\n"
"    border-image: url(:/Main/Submit Button.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.Submit.setText("")
        self.Submit.setObjectName("Submit")
        self.scopeOutput_Diskrit = QtWidgets.QPushButton(self.centralwidget)
        self.scopeOutput_Diskrit.setGeometry(QtCore.QRect(1140, 360, 79, 100))
        self.scopeOutput_Diskrit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scopeOutput_Diskrit.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/Main/Scope.png);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"}")
        self.scopeOutput_Diskrit.setText("")
        self.scopeOutput_Diskrit.setObjectName("scopeOutput_Diskrit")
        self.Overshoot = QtWidgets.QLineEdit(self.centralwidget)
        self.Overshoot.setGeometry(QtCore.QRect(50, 140, 113, 20))
        self.Overshoot.setReadOnly(True)
        self.Overshoot.setObjectName("Overshoot")
        self.TimeS = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeS.setGeometry(QtCore.QRect(50, 200, 113, 20))
        self.TimeS.setReadOnly(True)
        self.TimeS.setObjectName("TimeS")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 111, 30))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 170, 181, 30))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.frame.raise_()
        self.Refrensi.raise_()
        self.Controller.raise_()
        self.Plant.raise_()
        self.scopeOutput.raise_()
        self.scopeController.raise_()
        self.scopeOutput_Diskrit.raise_()
        self.Overshoot.raise_()
        self.TimeS.raise_()
        self.label_2.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Overshoot"))
        self.label.setText(_translate("MainWindow", "Time Settling"))
