# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul3/ui/PIDparam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(216, 178)
        MainWindow.setStyleSheet("background-color: rgb(226, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LKp = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LKp.setFont(font)
        self.LKp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.LKp.setText("")
        self.LKp.setObjectName("LKp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LKp)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LKi = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LKi.setFont(font)
        self.LKi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.LKi.setObjectName("LKi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LKi)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LKd = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LKd.setFont(font)
        self.LKd.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.LKd.setObjectName("LKd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LKd)
        self.updatePID = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.updatePID.setFont(font)
        self.updatePID.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatePID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 30px;\n"
"color: rgb(214, 0, 0);\n"
"font-size: 15px;\n"
"padding:7px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: normal; \n"
"    font-style: normal;")
        self.updatePID.setObjectName("updatePID")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.updatePID)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Kp"))
        self.label.setText(_translate("MainWindow", "Ki"))
        self.label_3.setText(_translate("MainWindow", "Kd"))
        self.updatePID.setText(_translate("MainWindow", "Update"))
