# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul3/ui/TransferFunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 142)
        MainWindow.setStyleSheet("background-color: rgb(226, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Num = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Num.setFont(font)
        self.Num.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Num.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"border : none;\n"
"padding-bottom:0px;\n"
"font-size: 30px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.Num.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Num.setReadOnly(True)
        self.Num.setObjectName("Num")
        self.verticalLayout.addWidget(self.Num)
        self.garis = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.garis.setFont(font)
        self.garis.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding : 0px;\n"
"\n"
"font-size: 30px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.garis.setAlignment(QtCore.Qt.AlignCenter)
        self.garis.setObjectName("garis")
        self.verticalLayout.addWidget(self.garis)
        self.Den = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Den.setFont(font)
        self.Den.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"border : none;\n"
"padding-bottom:0px;\n"
"font-size: 30px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.Den.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Den.setReadOnly(True)
        self.Den.setObjectName("Den")
        self.verticalLayout.addWidget(self.Den)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Num.setText(_translate("MainWindow", "1"))
        self.garis.setText(_translate("MainWindow", "--------------------------"))
        self.Den.setText(_translate("MainWindow", "(S+1)(s+3)"))
