# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Home/UI_home/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_2.setStyleSheet("border-image: url(:/Asset/Asset/LoginPage.png);\n"
"border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LoginPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.LoginPage)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 81 30pt \"Poppins\";\n"
"font-weight: bold; \n"
"color: rgb(214, 0, 0);\n"
"border: none;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.LoginGoogle = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LoginGoogle.setFont(font)
        self.LoginGoogle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginGoogle.setStyleSheet("QPushButton {\n"
"         \n"
"        background-color: rgba(214, 0, 0,255);\n"
"        border-radius : 5px;\n"
"        color: rgb(255, 255, 255);\n"
"        padding-top:5px;\n"
"        font: 16pt \"Poppins\";\n"
"        font-weight: bold;\n"
"        padding-top: 7px;\n"
"        padding-bottom: 7px; \n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    background-color: rgba(214, 0, 0,225);\n"
"};\n"
"border: none;")
        self.LoginGoogle.setObjectName("LoginGoogle")
        self.verticalLayout_8.addWidget(self.LoginGoogle)
        self.verticalLayout_9.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.frame_20)
        self.label_3.setStyleSheet("font: 12pt \"Poppins\";\n"
"font-weight: bold; \n"
"color: rgb(214, 0, 0);\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.frame_5 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_6.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/NPM.png);\n"
"border: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.Email = QtWidgets.QLineEdit(self.frame_5)
        self.Email.setMinimumSize(QtCore.QSize(0, 40))
        self.Email.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.Email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.Email.setPlaceholderText("")
        self.Email.setObjectName("Email")
        self.horizontalLayout_4.addWidget(self.Email)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.verticalLayout_9.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_10)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame_21)
        self.label_4.setStyleSheet("font: 12pt \"Poppins\";\n"
"font-weight: bold; \n"
"color: rgb(214, 0, 0);\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.frame = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setAcceptDrops(False)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_3.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/Pass.png);\n"
"border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.Pass = QtWidgets.QLineEdit(self.frame)
        self.Pass.setMinimumSize(QtCore.QSize(0, 40))
        self.Pass.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pass.setPlaceholderText("")
        self.Pass.setObjectName("Pass")
        self.horizontalLayout_2.addWidget(self.Pass)
        self.verticalLayout_11.addWidget(self.frame)
        self.verticalLayout_9.addWidget(self.frame_21)
        self.frame_8 = QtWidgets.QFrame(self.frame_10)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Login = QtWidgets.QPushButton(self.frame_8)
        self.Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login.setStyleSheet("QPushButton {\n"
"         \n"
"        background-color: rgba(214, 0, 0,255);\n"
"        border-radius : 5px;\n"
"        color: rgb(255, 255, 255);\n"
"        padding-top:5px;\n"
"        font: 20pt \"Poppins\";\n"
"        font-weight: bold;\n"
"        padding-top: 5px;\n"
"        padding-bottom: 5px; \n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    background-color: rgba(214, 0, 0,225);\n"
"};\n"
"border: none;")
        self.Login.setObjectName("Login")
        self.verticalLayout.addWidget(self.Login)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.ChangePass = QtWidgets.QPushButton(self.LoginPage)
        self.ChangePass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChangePass.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 255, 255,0);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 5px;\n"
"        color: rgb(214, 0, 0);        \n"
"        padding:0px;\n"
"        font: 8pt \"Poppins\";\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"};\n"
"border: none;")
        self.ChangePass.setObjectName("ChangePass")
        self.verticalLayout_2.addWidget(self.ChangePass)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.LoginPage)
        self.ChangePassPage = QtWidgets.QWidget()
        self.ChangePassPage.setObjectName("ChangePassPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ChangePassPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.ChangePassPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 81 30pt \"Poppins\";\n"
"font-weight: bold; \n"
"color: rgb(214, 0, 0);\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.frame_14 = QtWidgets.QFrame(self.ChangePassPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_15.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/NPM.png);\n"
"border: none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_6.addWidget(self.frame_15)
        self.EmailForgot = QtWidgets.QLineEdit(self.frame_14)
        self.EmailForgot.setMinimumSize(QtCore.QSize(0, 40))
        self.EmailForgot.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.EmailForgot.setObjectName("EmailForgot")
        self.horizontalLayout_6.addWidget(self.EmailForgot)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.ChangePassPage)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_16.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/Pass.png);\n"
"border: none;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_5.addWidget(self.frame_16)
        self.OldPass = QtWidgets.QLineEdit(self.frame_13)
        self.OldPass.setMinimumSize(QtCore.QSize(0, 40))
        self.OldPass.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.OldPass.setObjectName("OldPass")
        self.horizontalLayout_5.addWidget(self.OldPass)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.frame_4 = QtWidgets.QFrame(self.ChangePassPage)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_17 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_17.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/NewPass.png);\n"
"border: none;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.NewPass = QtWidgets.QLineEdit(self.frame_4)
        self.NewPass.setMinimumSize(QtCore.QSize(0, 40))
        self.NewPass.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.NewPass.setObjectName("NewPass")
        self.horizontalLayout_3.addWidget(self.NewPass)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_9 = QtWidgets.QFrame(self.ChangePassPage)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_18 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(70, 40))
        self.frame_18.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"padding : 2px;\n"
"image: url(:/Asset/Asset/ConfirmPass.png);\n"
"border: none;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_7.addWidget(self.frame_18)
        self.ConfirmPass = QtWidgets.QLineEdit(self.frame_9)
        self.ConfirmPass.setMinimumSize(QtCore.QSize(0, 40))
        self.ConfirmPass.setStyleSheet("background-color: rgba(214, 0, 0,100);\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgb(214, 0, 0);\n"
"border-right: 2px solid rgb(214, 0, 0);\n"
"border-top: 2px solid rgb(214, 0, 0);\n"
"padding-top:3px;\n"
"padding-left:10px;\n"
"font: 75 12pt \"Poppins\";\n"
"font-weight: bold;")
        self.ConfirmPass.setObjectName("ConfirmPass")
        self.horizontalLayout_7.addWidget(self.ConfirmPass)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.ChangePassPage)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Change = QtWidgets.QPushButton(self.frame_12)
        self.Change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Change.setStyleSheet("QPushButton {\n"
"         \n"
"        background-color: rgba(214, 0, 0,255);\n"
"        border-radius : 5px;\n"
"        color: rgb(255, 255, 255);\n"
"        padding-top:5px;\n"
"        font: 20pt \"Poppins\";\n"
"        font-weight: bold;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    background-color: rgba(214, 0, 0,225);\n"
"};\n"
"border: none;")
        self.Change.setObjectName("Change")
        self.verticalLayout_6.addWidget(self.Change)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.Back = QtWidgets.QPushButton(self.ChangePassPage)
        self.Back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Back.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 255, 255,0);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 5px;\n"
"        color: rgb(214, 0, 0);        \n"
"        padding:0px;\n"
"        font: 8pt \"Poppins\";\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"};\n"
"border: none;")
        self.Back.setObjectName("Back")
        self.verticalLayout_7.addWidget(self.Back)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.ChangePassPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome"))
        self.LoginGoogle.setText(_translate("MainWindow", "Login with Google"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.ChangePass.setText(_translate("MainWindow", "Change Password"))
        self.label_2.setText(_translate("MainWindow", "Change Pass"))
        self.EmailForgot.setPlaceholderText(_translate("MainWindow", "Enter Your Student ID"))
        self.OldPass.setPlaceholderText(_translate("MainWindow", "Enter Your Old Password"))
        self.NewPass.setPlaceholderText(_translate("MainWindow", "Enter Your New Password"))
        self.ConfirmPass.setPlaceholderText(_translate("MainWindow", "Confirm Your New Password"))
        self.Change.setText(_translate("MainWindow", "Change"))
        self.Back.setText(_translate("MainWindow", "Back to Login"))
