# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Home/UI_home/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border: none;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NavBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.NavBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NavBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.NavBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(70, 70))
        self.frame_3.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setStyleSheet("image: url(:/Asset/Asset/Logo Controllab 2026.png);\n"
"border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Practicum = QtWidgets.QPushButton(self.NavBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Practicum.sizePolicy().hasHeightForWidth())
        self.Practicum.setSizePolicy(sizePolicy)
        self.Practicum.setMinimumSize(QtCore.QSize(70, 70))
        self.Practicum.setMaximumSize(QtCore.QSize(100, 100))
        self.Practicum.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Practicum.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Lampu Mati.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Lampu Idup.png);\n"
"};\n"
"border: none;")
        self.Practicum.setText("")
        self.Practicum.setObjectName("Practicum")
        self.verticalLayout.addWidget(self.Practicum)
        self.Grade = QtWidgets.QPushButton(self.NavBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Grade.sizePolicy().hasHeightForWidth())
        self.Grade.setSizePolicy(sizePolicy)
        self.Grade.setMinimumSize(QtCore.QSize(70, 70))
        self.Grade.setMaximumSize(QtCore.QSize(100, 100))
        self.Grade.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Grade.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Chart kosong.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    image: url(:/Asset/Asset/Chart isi.png);\n"
"};\n"
"border: none;")
        self.Grade.setText("")
        self.Grade.setObjectName("Grade")
        self.verticalLayout.addWidget(self.Grade)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.LogOut = QtWidgets.QPushButton(self.NavBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogOut.sizePolicy().hasHeightForWidth())
        self.LogOut.setSizePolicy(sizePolicy)
        self.LogOut.setMinimumSize(QtCore.QSize(70, 70))
        self.LogOut.setMaximumSize(QtCore.QSize(100, 100))
        self.LogOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogOut.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Log Out 1.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    image: url(:/Asset/Asset/Log Out 2.png);\n"
"};\n"
"border: none;")
        self.LogOut.setText("")
        self.LogOut.setObjectName("LogOut")
        self.verticalLayout.addWidget(self.LogOut)
        self.horizontalLayout.addWidget(self.NavBar)
        self.Stacked = QtWidgets.QStackedWidget(self.centralwidget)
        self.Stacked.setMinimumSize(QtCore.QSize(1000, 0))
        self.Stacked.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.Stacked.setObjectName("Stacked")
        self.PracticumPage = QtWidgets.QWidget()
        self.PracticumPage.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border: none;")
        self.PracticumPage.setObjectName("PracticumPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PracticumPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_32 = QtWidgets.QFrame(self.PracticumPage)
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_107 = QtWidgets.QFrame(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_107.sizePolicy().hasHeightForWidth())
        self.frame_107.setSizePolicy(sizePolicy)
        self.frame_107.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_107.setMaximumSize(QtCore.QSize(222, 16777215))
        self.frame_107.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border: none;")
        self.frame_107.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_107.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_107.setObjectName("frame_107")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_107)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Kelompok2_2 = QtWidgets.QLabel(self.frame_107)
        self.Kelompok2_2.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;\n"
"border: none;")
        self.Kelompok2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Kelompok2_2.setObjectName("Kelompok2_2")
        self.horizontalLayout_27.addWidget(self.Kelompok2_2)
        self.horizontalLayout_9.addWidget(self.frame_107)
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setMinimumSize(QtCore.QSize(900, 50))
        self.frame_33.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border: none;")
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.WelcomeText = QtWidgets.QLabel(self.frame_33)
        self.WelcomeText.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;\n"
"border: none;")
        self.WelcomeText.setObjectName("WelcomeText")
        self.horizontalLayout_10.addWidget(self.WelcomeText)
        self.horizontalLayout_9.addWidget(self.frame_33)
        self.verticalLayout_2.addWidget(self.frame_32)
        self.frame_12 = QtWidgets.QFrame(self.PracticumPage)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 250))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 966, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RootLocus = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RootLocus.sizePolicy().hasHeightForWidth())
        self.RootLocus.setSizePolicy(sizePolicy)
        self.RootLocus.setMinimumSize(QtCore.QSize(150, 0))
        self.RootLocus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RootLocus.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 23.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.RootLocus.setText("")
        self.RootLocus.setObjectName("RootLocus")
        self.horizontalLayout_2.addWidget(self.RootLocus)
        self.FreqResponse = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FreqResponse.sizePolicy().hasHeightForWidth())
        self.FreqResponse.setSizePolicy(sizePolicy)
        self.FreqResponse.setMinimumSize(QtCore.QSize(150, 0))
        self.FreqResponse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FreqResponse.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 4.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.FreqResponse.setText("")
        self.FreqResponse.setObjectName("FreqResponse")
        self.horizontalLayout_2.addWidget(self.FreqResponse)
        self.CDFrequency = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CDFrequency.sizePolicy().hasHeightForWidth())
        self.CDFrequency.setSizePolicy(sizePolicy)
        self.CDFrequency.setMinimumSize(QtCore.QSize(150, 0))
        self.CDFrequency.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CDFrequency.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 5.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.CDFrequency.setText("")
        self.CDFrequency.setObjectName("CDFrequency")
        self.horizontalLayout_2.addWidget(self.CDFrequency)
        self.COD = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COD.sizePolicy().hasHeightForWidth())
        self.COD.setSizePolicy(sizePolicy)
        self.COD.setMinimumSize(QtCore.QSize(150, 0))
        self.COD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.COD.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 6.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.COD.setText("")
        self.COD.setObjectName("COD")
        self.horizontalLayout_2.addWidget(self.COD)
        self.DiscreteCOD = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiscreteCOD.sizePolicy().hasHeightForWidth())
        self.DiscreteCOD.setSizePolicy(sizePolicy)
        self.DiscreteCOD.setMinimumSize(QtCore.QSize(150, 0))
        self.DiscreteCOD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DiscreteCOD.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 8.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.DiscreteCOD.setText("")
        self.DiscreteCOD.setObjectName("DiscreteCOD")
        self.horizontalLayout_2.addWidget(self.DiscreteCOD)
        self.DCMotor = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCMotor.sizePolicy().hasHeightForWidth())
        self.DCMotor.setSizePolicy(sizePolicy)
        self.DCMotor.setMinimumSize(QtCore.QSize(150, 0))
        self.DCMotor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DCMotor.setStyleSheet("QPushButton {\n"
"    image: url(:/Asset/Asset/Modul 910.png);\n"
"    border: 0px;\n"
"    border-radius : 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    padding: 10px;\n"
"};\n"
"border: none;")
        self.DCMotor.setText("")
        self.DCMotor.setObjectName("DCMotor")
        self.horizontalLayout_2.addWidget(self.DCMotor)
        self.verticalLayout_30.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.FirstPage = QtWidgets.QWidget()
        self.FirstPage.setStyleSheet("image: url(:/Asset/Asset/Header.png);\n"
"border: none;")
        self.FirstPage.setObjectName("FirstPage")
        self.stackedWidget.addWidget(self.FirstPage)
        self.RootLocusPage = QtWidgets.QWidget()
        self.RootLocusPage.setObjectName("RootLocusPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.RootLocusPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.RootLocusPage)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.RootLocusPage)
        self.frame_2.setStyleSheet("\n"
"border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_13.setStyleSheet("image: url(:/Asset/Asset/Modul 23.png);\n"
"border: none;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setStyleSheet("image: url(:/Asset/Asset/Root Locus.png);\n"
"border: none;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_6.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setStyleSheet("image: url(:/Asset/Asset/VPID.png);\n"
"border: none;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_6.addWidget(self.frame_16)
        self.horizontalLayout_4.addWidget(self.frame_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.frame_15 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_15.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.RunRL = QtWidgets.QPushButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunRL.sizePolicy().hasHeightForWidth())
        self.RunRL.setSizePolicy(sizePolicy)
        self.RunRL.setMinimumSize(QtCore.QSize(0, 141))
        self.RunRL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunRL.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunRL.setText("")
        self.RunRL.setObjectName("RunRL")
        self.verticalLayout_5.addWidget(self.RunRL)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.RunCDRL = QtWidgets.QPushButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunCDRL.sizePolicy().hasHeightForWidth())
        self.RunCDRL.setSizePolicy(sizePolicy)
        self.RunCDRL.setMinimumSize(QtCore.QSize(0, 141))
        self.RunCDRL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunCDRL.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunCDRL.setText("")
        self.RunCDRL.setObjectName("RunCDRL")
        self.verticalLayout_5.addWidget(self.RunCDRL)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_4.addWidget(self.frame_15)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.RootLocusPage)
        self.FreqResponsePage = QtWidgets.QWidget()
        self.FreqResponsePage.setObjectName("FreqResponsePage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.FreqResponsePage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_24 = QtWidgets.QFrame(self.FreqResponsePage)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_26 = QtWidgets.QFrame(self.frame_24)
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_6.addWidget(self.frame_26)
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        self.frame_25.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_6.addWidget(self.frame_25)
        self.frame_27 = QtWidgets.QFrame(self.frame_24)
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_6.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_24)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_6.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.frame_24)
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_6.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_24)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_6.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_24)
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_6.addWidget(self.frame_31)
        self.verticalLayout_9.addWidget(self.frame_24)
        self.frame_18 = QtWidgets.QFrame(self.FreqResponsePage)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_19.setStyleSheet("image: url(:/Asset/Asset/Modul 4.png);\n"
"border: none;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_5.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("image: url(:/Asset/Asset/FreqResp.png);\n"
"border: none;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_7.addWidget(self.frame_21)
        self.horizontalLayout_5.addWidget(self.frame_20)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.frame_23 = QtWidgets.QFrame(self.frame_18)
        self.frame_23.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_23.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.RunFreq = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunFreq.sizePolicy().hasHeightForWidth())
        self.RunFreq.setSizePolicy(sizePolicy)
        self.RunFreq.setMinimumSize(QtCore.QSize(0, 141))
        self.RunFreq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunFreq.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunFreq.setText("")
        self.RunFreq.setObjectName("RunFreq")
        self.verticalLayout_8.addWidget(self.RunFreq)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_5.addWidget(self.frame_23)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.FreqResponsePage)
        self.CDFreqPage = QtWidgets.QWidget()
        self.CDFreqPage.setObjectName("CDFreqPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.CDFreqPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_35 = QtWidgets.QFrame(self.CDFreqPage)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_7.addWidget(self.frame_36)
        self.frame_38 = QtWidgets.QFrame(self.frame_35)
        self.frame_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_7.addWidget(self.frame_38)
        self.frame_37 = QtWidgets.QFrame(self.frame_35)
        self.frame_37.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_7.addWidget(self.frame_37)
        self.frame_39 = QtWidgets.QFrame(self.frame_35)
        self.frame_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_7.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_35)
        self.frame_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_7.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_35)
        self.frame_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_7.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_35)
        self.frame_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_7.addWidget(self.frame_42)
        self.verticalLayout_12.addWidget(self.frame_35)
        self.frame_22 = QtWidgets.QFrame(self.CDFreqPage)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_43 = QtWidgets.QFrame(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_43.sizePolicy().hasHeightForWidth())
        self.frame_43.setSizePolicy(sizePolicy)
        self.frame_43.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_43.setStyleSheet("image: url(:/Asset/Asset/Modul 5.png);\n"
"border: none;")
        self.frame_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_8.addWidget(self.frame_43)
        self.frame_44 = QtWidgets.QFrame(self.frame_22)
        self.frame_44.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_45 = QtWidgets.QFrame(self.frame_44)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_45.sizePolicy().hasHeightForWidth())
        self.frame_45.setSizePolicy(sizePolicy)
        self.frame_45.setStyleSheet("image: url(:/Asset/Asset/CDFreq.png);\n"
"border: none;")
        self.frame_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_10.addWidget(self.frame_45)
        self.horizontalLayout_8.addWidget(self.frame_44)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.frame_46 = QtWidgets.QFrame(self.frame_22)
        self.frame_46.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_46.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.RunCDFreq = QtWidgets.QPushButton(self.frame_46)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunCDFreq.sizePolicy().hasHeightForWidth())
        self.RunCDFreq.setSizePolicy(sizePolicy)
        self.RunCDFreq.setMinimumSize(QtCore.QSize(0, 141))
        self.RunCDFreq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunCDFreq.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunCDFreq.setText("")
        self.RunCDFreq.setObjectName("RunCDFreq")
        self.verticalLayout_11.addWidget(self.RunCDFreq)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.horizontalLayout_8.addWidget(self.frame_46)
        self.verticalLayout_12.addWidget(self.frame_22)
        self.stackedWidget.addWidget(self.CDFreqPage)
        self.StateSpaceModelAndDesignPage = QtWidgets.QWidget()
        self.StateSpaceModelAndDesignPage.setObjectName("StateSpaceModelAndDesignPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.StateSpaceModelAndDesignPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_52 = QtWidgets.QFrame(self.StateSpaceModelAndDesignPage)
        self.frame_52.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_52.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_53 = QtWidgets.QFrame(self.frame_52)
        self.frame_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_13.addWidget(self.frame_53)
        self.frame_54 = QtWidgets.QFrame(self.frame_52)
        self.frame_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_13.addWidget(self.frame_54)
        self.frame_56 = QtWidgets.QFrame(self.frame_52)
        self.frame_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_13.addWidget(self.frame_56)
        self.frame_55 = QtWidgets.QFrame(self.frame_52)
        self.frame_55.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.horizontalLayout_13.addWidget(self.frame_55)
        self.frame_57 = QtWidgets.QFrame(self.frame_52)
        self.frame_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_13.addWidget(self.frame_57)
        self.frame_58 = QtWidgets.QFrame(self.frame_52)
        self.frame_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.horizontalLayout_13.addWidget(self.frame_58)
        self.frame_59 = QtWidgets.QFrame(self.frame_52)
        self.frame_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.horizontalLayout_13.addWidget(self.frame_59)
        self.verticalLayout_15.addWidget(self.frame_52)
        self.frame_47 = QtWidgets.QFrame(self.StateSpaceModelAndDesignPage)
        self.frame_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_48 = QtWidgets.QFrame(self.frame_47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_48.sizePolicy().hasHeightForWidth())
        self.frame_48.setSizePolicy(sizePolicy)
        self.frame_48.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_12.addWidget(self.frame_48)
        self.frame_49 = QtWidgets.QFrame(self.frame_47)
        self.frame_49.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_50.sizePolicy().hasHeightForWidth())
        self.frame_50.setSizePolicy(sizePolicy)
        self.frame_50.setStyleSheet("image: url(:/Asset/Asset/SSM.png);\n"
"border: none;")
        self.frame_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_13.addWidget(self.frame_50)
        self.horizontalLayout_12.addWidget(self.frame_49)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.frame_51 = QtWidgets.QFrame(self.frame_47)
        self.frame_51.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_51.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.RunStateSpace = QtWidgets.QPushButton(self.frame_51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunStateSpace.sizePolicy().hasHeightForWidth())
        self.RunStateSpace.setSizePolicy(sizePolicy)
        self.RunStateSpace.setMinimumSize(QtCore.QSize(0, 141))
        self.RunStateSpace.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunStateSpace.setText("")
        self.RunStateSpace.setObjectName("RunStateSpace")
        self.verticalLayout_14.addWidget(self.RunStateSpace)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.horizontalLayout_12.addWidget(self.frame_51)
        self.verticalLayout_15.addWidget(self.frame_47)
        self.stackedWidget.addWidget(self.StateSpaceModelAndDesignPage)
        self.ShouldBeEmptyPage = QtWidgets.QWidget()
        self.ShouldBeEmptyPage.setObjectName("ShouldBeEmptyPage")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.ShouldBeEmptyPage)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_65 = QtWidgets.QFrame(self.ShouldBeEmptyPage)
        self.frame_65.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_65.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_65.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_65)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_66 = QtWidgets.QFrame(self.frame_65)
        self.frame_66.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_66.setObjectName("frame_66")
        self.horizontalLayout_15.addWidget(self.frame_66)
        self.frame_67 = QtWidgets.QFrame(self.frame_65)
        self.frame_67.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.horizontalLayout_15.addWidget(self.frame_67)
        self.frame_69 = QtWidgets.QFrame(self.frame_65)
        self.frame_69.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.horizontalLayout_15.addWidget(self.frame_69)
        self.frame_70 = QtWidgets.QFrame(self.frame_65)
        self.frame_70.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_70.setObjectName("frame_70")
        self.horizontalLayout_15.addWidget(self.frame_70)
        self.frame_68 = QtWidgets.QFrame(self.frame_65)
        self.frame_68.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_68.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.horizontalLayout_15.addWidget(self.frame_68)
        self.frame_71 = QtWidgets.QFrame(self.frame_65)
        self.frame_71.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_71.setObjectName("frame_71")
        self.horizontalLayout_15.addWidget(self.frame_71)
        self.frame_72 = QtWidgets.QFrame(self.frame_65)
        self.frame_72.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.horizontalLayout_15.addWidget(self.frame_72)
        self.verticalLayout_18.addWidget(self.frame_65)
        self.frame_60 = QtWidgets.QFrame(self.ShouldBeEmptyPage)
        self.frame_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_60)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_61 = QtWidgets.QFrame(self.frame_60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_61.sizePolicy().hasHeightForWidth())
        self.frame_61.setSizePolicy(sizePolicy)
        self.frame_61.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_61.setStyleSheet("image: url(:/Asset/Asset/Modul 6.png);\n"
"border: none;")
        self.frame_61.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.horizontalLayout_14.addWidget(self.frame_61)
        self.frame_62 = QtWidgets.QFrame(self.frame_60)
        self.frame_62.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_62.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_62)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_63 = QtWidgets.QFrame(self.frame_62)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_63.sizePolicy().hasHeightForWidth())
        self.frame_63.setSizePolicy(sizePolicy)
        self.frame_63.setStyleSheet("image: url(:/Asset/Asset/Continuous.png);\n"
"border: none;")
        self.frame_63.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.verticalLayout_16.addWidget(self.frame_63)
        self.horizontalLayout_14.addWidget(self.frame_62)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.frame_64 = QtWidgets.QFrame(self.frame_60)
        self.frame_64.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_64.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_64.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_64)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem16)
        self.RunCOD = QtWidgets.QPushButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunCOD.sizePolicy().hasHeightForWidth())
        self.RunCOD.setSizePolicy(sizePolicy)
        self.RunCOD.setMinimumSize(QtCore.QSize(0, 141))
        self.RunCOD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunCOD.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunCOD.setText("")
        self.RunCOD.setObjectName("RunCOD")
        self.verticalLayout_17.addWidget(self.RunCOD)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem17)
        self.horizontalLayout_14.addWidget(self.frame_64)
        self.verticalLayout_18.addWidget(self.frame_60)
        self.stackedWidget.addWidget(self.ShouldBeEmptyPage)
        self.DiscreteCDPage = QtWidgets.QWidget()
        self.DiscreteCDPage.setObjectName("DiscreteCDPage")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.DiscreteCDPage)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_78 = QtWidgets.QFrame(self.DiscreteCDPage)
        self.frame_78.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_78.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_78.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_78.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_78.setObjectName("frame_78")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_78)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_79 = QtWidgets.QFrame(self.frame_78)
        self.frame_79.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_79.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_79.setObjectName("frame_79")
        self.horizontalLayout_17.addWidget(self.frame_79)
        self.frame_80 = QtWidgets.QFrame(self.frame_78)
        self.frame_80.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_80.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_80.setObjectName("frame_80")
        self.horizontalLayout_17.addWidget(self.frame_80)
        self.frame_82 = QtWidgets.QFrame(self.frame_78)
        self.frame_82.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_82.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_82.setObjectName("frame_82")
        self.horizontalLayout_17.addWidget(self.frame_82)
        self.frame_83 = QtWidgets.QFrame(self.frame_78)
        self.frame_83.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_83.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_83.setObjectName("frame_83")
        self.horizontalLayout_17.addWidget(self.frame_83)
        self.frame_84 = QtWidgets.QFrame(self.frame_78)
        self.frame_84.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_84.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_84.setObjectName("frame_84")
        self.horizontalLayout_17.addWidget(self.frame_84)
        self.frame_81 = QtWidgets.QFrame(self.frame_78)
        self.frame_81.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_81.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_81.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_81.setObjectName("frame_81")
        self.horizontalLayout_17.addWidget(self.frame_81)
        self.frame_85 = QtWidgets.QFrame(self.frame_78)
        self.frame_85.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_85.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_85.setObjectName("frame_85")
        self.horizontalLayout_17.addWidget(self.frame_85)
        self.verticalLayout_21.addWidget(self.frame_78)
        self.frame_73 = QtWidgets.QFrame(self.DiscreteCDPage)
        self.frame_73.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_73)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_74 = QtWidgets.QFrame(self.frame_73)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_74.sizePolicy().hasHeightForWidth())
        self.frame_74.setSizePolicy(sizePolicy)
        self.frame_74.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_74.setStyleSheet("image: url(:/Asset/Asset/Modul 8.png);\n"
"border: none;")
        self.frame_74.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_74.setObjectName("frame_74")
        self.horizontalLayout_16.addWidget(self.frame_74)
        self.frame_75 = QtWidgets.QFrame(self.frame_73)
        self.frame_75.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_75.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_75.setObjectName("frame_75")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_75)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_76 = QtWidgets.QFrame(self.frame_75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_76.sizePolicy().hasHeightForWidth())
        self.frame_76.setSizePolicy(sizePolicy)
        self.frame_76.setStyleSheet("image: url(:/Asset/Asset/Discrete.png);\n"
"border: none;")
        self.frame_76.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_76.setObjectName("frame_76")
        self.verticalLayout_19.addWidget(self.frame_76)
        self.horizontalLayout_16.addWidget(self.frame_75)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem18)
        self.frame_77 = QtWidgets.QFrame(self.frame_73)
        self.frame_77.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_77.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_77.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_77.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_77.setObjectName("frame_77")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_77)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem19)
        self.RunDCOD = QtWidgets.QPushButton(self.frame_77)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunDCOD.sizePolicy().hasHeightForWidth())
        self.RunDCOD.setSizePolicy(sizePolicy)
        self.RunDCOD.setMinimumSize(QtCore.QSize(0, 141))
        self.RunDCOD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunDCOD.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunDCOD.setText("")
        self.RunDCOD.setObjectName("RunDCOD")
        self.verticalLayout_20.addWidget(self.RunDCOD)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem20)
        self.horizontalLayout_16.addWidget(self.frame_77)
        self.verticalLayout_21.addWidget(self.frame_73)
        self.stackedWidget.addWidget(self.DiscreteCDPage)
        self.DCMotorModelAndDesignPage = QtWidgets.QWidget()
        self.DCMotorModelAndDesignPage.setObjectName("DCMotorModelAndDesignPage")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.DCMotorModelAndDesignPage)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_91 = QtWidgets.QFrame(self.DCMotorModelAndDesignPage)
        self.frame_91.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_91.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_91.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_91.setObjectName("frame_91")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_91)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_92 = QtWidgets.QFrame(self.frame_91)
        self.frame_92.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_92.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_92.setObjectName("frame_92")
        self.horizontalLayout_19.addWidget(self.frame_92)
        self.frame_93 = QtWidgets.QFrame(self.frame_91)
        self.frame_93.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_93.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_93.setObjectName("frame_93")
        self.horizontalLayout_19.addWidget(self.frame_93)
        self.frame_95 = QtWidgets.QFrame(self.frame_91)
        self.frame_95.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_95.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_95.setObjectName("frame_95")
        self.horizontalLayout_19.addWidget(self.frame_95)
        self.frame_96 = QtWidgets.QFrame(self.frame_91)
        self.frame_96.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_96.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_96.setObjectName("frame_96")
        self.horizontalLayout_19.addWidget(self.frame_96)
        self.frame_97 = QtWidgets.QFrame(self.frame_91)
        self.frame_97.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_97.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_97.setObjectName("frame_97")
        self.horizontalLayout_19.addWidget(self.frame_97)
        self.frame_98 = QtWidgets.QFrame(self.frame_91)
        self.frame_98.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_98.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_98.setObjectName("frame_98")
        self.horizontalLayout_19.addWidget(self.frame_98)
        self.frame_94 = QtWidgets.QFrame(self.frame_91)
        self.frame_94.setStyleSheet("background-color: rgb(8, 29, 56);\n"
"border-radius : 5px;\n"
"border: none;")
        self.frame_94.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_94.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_94.setObjectName("frame_94")
        self.horizontalLayout_19.addWidget(self.frame_94)
        self.verticalLayout_24.addWidget(self.frame_91)
        self.frame_86 = QtWidgets.QFrame(self.DCMotorModelAndDesignPage)
        self.frame_86.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_86.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_86.setObjectName("frame_86")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_86)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_87 = QtWidgets.QFrame(self.frame_86)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_87.sizePolicy().hasHeightForWidth())
        self.frame_87.setSizePolicy(sizePolicy)
        self.frame_87.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_87.setStyleSheet("image: url(:/Asset/Asset/Modul 910.png);\n"
"border: none;")
        self.frame_87.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_87.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_87.setObjectName("frame_87")
        self.horizontalLayout_18.addWidget(self.frame_87)
        self.frame_88 = QtWidgets.QFrame(self.frame_86)
        self.frame_88.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_88.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_88.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_88.setObjectName("frame_88")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_88)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_89 = QtWidgets.QFrame(self.frame_88)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_89.sizePolicy().hasHeightForWidth())
        self.frame_89.setSizePolicy(sizePolicy)
        self.frame_89.setStyleSheet("image: url(:/Asset/Asset/Motor.png);\n"
"border: none;")
        self.frame_89.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_89.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_89.setObjectName("frame_89")
        self.verticalLayout_22.addWidget(self.frame_89)
        self.horizontalLayout_18.addWidget(self.frame_88)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem21)
        self.frame_90 = QtWidgets.QFrame(self.frame_86)
        self.frame_90.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_90.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_90.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_90.setObjectName("frame_90")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_90)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem22)
        self.RunMotor = QtWidgets.QPushButton(self.frame_90)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunMotor.sizePolicy().hasHeightForWidth())
        self.RunMotor.setSizePolicy(sizePolicy)
        self.RunMotor.setMinimumSize(QtCore.QSize(0, 141))
        self.RunMotor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RunMotor.setStyleSheet("QPushButton {\n"
"         background-color: rgba(255, 220, 50, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"        font-size: 40px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgba(222, 191, 42, 225);\n"
"};\n"
"border: none;")
        self.RunMotor.setText("")
        self.RunMotor.setObjectName("RunMotor")
        self.verticalLayout_23.addWidget(self.RunMotor)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem23)
        self.horizontalLayout_18.addWidget(self.frame_90)
        self.verticalLayout_24.addWidget(self.frame_86)
        self.stackedWidget.addWidget(self.DCMotorModelAndDesignPage)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.Stacked.addWidget(self.PracticumPage)
        self.horizontalLayout.addWidget(self.Stacked)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Stacked.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Kelompok2_2.setText(_translate("MainWindow", "1"))
        self.WelcomeText.setText(_translate("MainWindow", "Welcome Attafahqi Amirtha Dariswan!"))
