# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul8/ui_8/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(:/desain/bgasliril.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QFrame(self.centralwidget)
        self.leftMenu.setMaximumSize(QtCore.QSize(395, 16777215))
        self.leftMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.leftMenu)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.stackedWidget.setStyleSheet("/* Background utama stack widget */\n"
"QStackedWidget {\n"
"    background-color: #FFFFFF;   /* putih bersih */\n"
"    border: none;\n"
"}\n"
"\n"
"/* Tombol kiri dan kanan dibuat “melebur” dengan background */\n"
"QPushButton#btnPrev,\n"
"QPushButton#btnNext {\n"
"    background-color: transparent;   /* menyatu */\n"
"    border: none;\n"
"    color: #444444;                  /* warna ikon/text */\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"/* Hover minimalis */\n"
"QPushButton#btnPrev:hover,\n"
"QPushButton#btnNext:hover {\n"
"    background-color: rgba(0,0,0,0.04);   /* bayangan halus */\n"
"    border-radius: 4px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftMotorPG = QtWidgets.QPushButton(self.page)
        self.leftMotorPG.setMaximumSize(QtCore.QSize(50, 50))
        self.leftMotorPG.setObjectName("leftMotorPG")
        self.horizontalLayout_5.addWidget(self.leftMotorPG)
        self.motorButton = QtWidgets.QPushButton(self.page)
        self.motorButton.setMinimumSize(QtCore.QSize(200, 100))
        self.motorButton.setMaximumSize(QtCore.QSize(300, 300))
        self.motorButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/desain/Motor.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Hover: abu muda transparan = efek buram elegan */\n"
"QPushButton:hover {\n"
"    background-color: rgba(220, 220, 220, 0.35);   /* abu muda */\n"
"}\n"
"\n"
"/* Pressed: abu sedikit lebih tebal */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 0.50);\n"
"}\n"
"")
        self.motorButton.setText("")
        self.motorButton.setObjectName("motorButton")
        self.horizontalLayout_5.addWidget(self.motorButton)
        self.rightMotorPG = QtWidgets.QPushButton(self.page)
        self.rightMotorPG.setMaximumSize(QtCore.QSize(50, 50))
        self.rightMotorPG.setObjectName("rightMotorPG")
        self.horizontalLayout_5.addWidget(self.rightMotorPG)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftDamperPG = QtWidgets.QPushButton(self.page_1)
        self.leftDamperPG.setMaximumSize(QtCore.QSize(50, 50))
        self.leftDamperPG.setObjectName("leftDamperPG")
        self.horizontalLayout_2.addWidget(self.leftDamperPG)
        self.damperButton = QtWidgets.QPushButton(self.page_1)
        self.damperButton.setMinimumSize(QtCore.QSize(200, 100))
        self.damperButton.setMaximumSize(QtCore.QSize(300, 300))
        self.damperButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/desain/Damper.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Hover: abu muda transparan = efek buram elegan */\n"
"QPushButton:hover {\n"
"    background-color: rgba(220, 220, 220, 0.35);   /* abu muda */\n"
"}\n"
"\n"
"/* Pressed: abu sedikit lebih tebal */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 0.50);\n"
"}\n"
"")
        self.damperButton.setText("")
        self.damperButton.setObjectName("damperButton")
        self.horizontalLayout_2.addWidget(self.damperButton)
        self.rightDamperPG = QtWidgets.QPushButton(self.page_1)
        self.rightDamperPG.setMaximumSize(QtCore.QSize(50, 50))
        self.rightDamperPG.setObjectName("rightDamperPG")
        self.horizontalLayout_2.addWidget(self.rightDamperPG)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leftBuckPG = QtWidgets.QPushButton(self.page_2)
        self.leftBuckPG.setMaximumSize(QtCore.QSize(50, 50))
        self.leftBuckPG.setObjectName("leftBuckPG")
        self.horizontalLayout_3.addWidget(self.leftBuckPG)
        self.buckButton = QtWidgets.QPushButton(self.page_2)
        self.buckButton.setMinimumSize(QtCore.QSize(200, 200))
        self.buckButton.setMaximumSize(QtCore.QSize(300, 200))
        self.buckButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/desain/buck.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Hover: abu muda transparan = efek buram elegan */\n"
"QPushButton:hover {\n"
"    background-color: rgba(220, 220, 220, 0.35);   /* abu muda */\n"
"}\n"
"\n"
"/* Pressed: abu sedikit lebih tebal */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 0.50);\n"
"}\n"
"")
        self.buckButton.setText("")
        self.buckButton.setObjectName("buckButton")
        self.horizontalLayout_3.addWidget(self.buckButton)
        self.rightBuckPG = QtWidgets.QPushButton(self.page_2)
        self.rightBuckPG.setMaximumSize(QtCore.QSize(50, 50))
        self.rightBuckPG.setObjectName("rightBuckPG")
        self.horizontalLayout_3.addWidget(self.rightBuckPG)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.userInput = QtWidgets.QFrame(self.leftMenu)
        self.userInput.setMinimumSize(QtCore.QSize(0, 300))
        self.userInput.setMaximumSize(QtCore.QSize(16777215, 300))
        self.userInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.userInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userInput.setObjectName("userInput")
        self.gridLayout = QtWidgets.QGridLayout(self.userInput)
        self.gridLayout.setObjectName("gridLayout")
        self.rLabel = QtWidgets.QLabel(self.userInput)
        self.rLabel.setStyleSheet("QLabel{\n"
"    font-family: \"Poppins Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.rLabel.setObjectName("rLabel")
        self.gridLayout.addWidget(self.rLabel, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lLabel = QtWidgets.QLabel(self.userInput)
        self.lLabel.setStyleSheet("QLabel{\n"
"    font-family: \"Poppins Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lLabel.setObjectName("lLabel")
        self.gridLayout.addWidget(self.lLabel, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.nLabel = QtWidgets.QLabel(self.userInput)
        self.nLabel.setStyleSheet("QLabel{\n"
"    font-family: \"Poppins Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.nLabel.setObjectName("nLabel")
        self.gridLayout.addWidget(self.nLabel, 7, 5, 1, 1, QtCore.Qt.AlignRight)
        self.matrixBLabel = QtWidgets.QLabel(self.userInput)
        self.matrixBLabel.setStyleSheet("QLabel{\n"
"    font-family: \"Poppins Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.matrixBLabel.setObjectName("matrixBLabel")
        self.gridLayout.addWidget(self.matrixBLabel, 1, 5, 1, 1, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.n = QtWidgets.QLineEdit(self.userInput)
        self.n.setMaximumSize(QtCore.QSize(80, 35))
        self.n.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.n.setObjectName("n")
        self.gridLayout.addWidget(self.n, 7, 6, 1, 1)
        self.r2 = QtWidgets.QLineEdit(self.userInput)
        self.r2.setMaximumSize(QtCore.QSize(80, 35))
        self.r2.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.r2.setObjectName("r2")
        self.gridLayout.addWidget(self.r2, 7, 2, 1, 1)
        self.b21 = QtWidgets.QLineEdit(self.userInput)
        self.b21.setMaximumSize(QtCore.QSize(80, 35))
        self.b21.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.b21.setObjectName("b21")
        self.gridLayout.addWidget(self.b21, 2, 6, 1, 1)
        self.a12 = QtWidgets.QLineEdit(self.userInput)
        self.a12.setMaximumSize(QtCore.QSize(100, 35))
        self.a12.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.a12.setObjectName("a12")
        self.gridLayout.addWidget(self.a12, 1, 2, 1, 1)
        self.a11 = QtWidgets.QLineEdit(self.userInput)
        self.a11.setMaximumSize(QtCore.QSize(100, 35))
        self.a11.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.a11.setText("")
        self.a11.setObjectName("a11")
        self.gridLayout.addWidget(self.a11, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.a21 = QtWidgets.QLineEdit(self.userInput)
        self.a21.setMaximumSize(QtCore.QSize(100, 35))
        self.a21.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.a21.setObjectName("a21")
        self.gridLayout.addWidget(self.a21, 2, 1, 1, 1)
        self.r1 = QtWidgets.QLineEdit(self.userInput)
        self.r1.setMaximumSize(QtCore.QSize(80, 35))
        self.r1.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.r1.setObjectName("r1")
        self.gridLayout.addWidget(self.r1, 7, 1, 1, 1)
        self.l2 = QtWidgets.QLineEdit(self.userInput)
        self.l2.setMaximumSize(QtCore.QSize(80, 35))
        self.l2.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 5, 2, 1, 1)
        self.matrixALabel = QtWidgets.QLabel(self.userInput)
        self.matrixALabel.setStyleSheet("QLabel{\n"
"    font-family: \"Poppins Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.matrixALabel.setObjectName("matrixALabel")
        self.gridLayout.addWidget(self.matrixALabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.l1 = QtWidgets.QLineEdit(self.userInput)
        self.l1.setMaximumSize(QtCore.QSize(80, 35))
        self.l1.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 5, 1, 1, 1)
        self.a22 = QtWidgets.QLineEdit(self.userInput)
        self.a22.setMaximumSize(QtCore.QSize(100, 35))
        self.a22.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.a22.setObjectName("a22")
        self.gridLayout.addWidget(self.a22, 2, 2, 1, 1)
        self.b11 = QtWidgets.QLineEdit(self.userInput)
        self.b11.setMaximumSize(QtCore.QSize(100, 35))
        self.b11.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.b11.setObjectName("b11")
        self.gridLayout.addWidget(self.b11, 1, 6, 1, 1)
        self.verticalLayout.addWidget(self.userInput)
        self.frame = QtWidgets.QFrame(self.leftMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(115, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    font-size: 16pt;\n"
"    color: #000000;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.setpoint = QtWidgets.QLineEdit(self.frame)
        self.setpoint.setMaximumSize(QtCore.QSize(100, 35))
        self.setpoint.setStyleSheet("QLineEdit {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"\n"
"    background-color: #F2F2F2;        /* abu-abu muda elegan */\n"
"    border: 1px solid #D0D0D0;        /* outline halus */\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 6px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0A0A0;        /* highlight tipis saat fokus */\n"
"}")
        self.setpoint.setObjectName("setpoint")
        self.horizontalLayout_4.addWidget(self.setpoint)
        self.unitLabel = QtWidgets.QLabel(self.frame)
        self.unitLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setItalic(True)
        self.unitLabel.setFont(font)
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_4.addWidget(self.unitLabel)
        self.verticalLayout.addWidget(self.frame)
        self.leftButtonFrame = QtWidgets.QHBoxLayout()
        self.leftButtonFrame.setObjectName("leftButtonFrame")
        self.saveButton = QtWidgets.QPushButton(self.leftMenu)
        self.saveButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"    color: #FFFFFF;\n"
"\n"
"    background-color: #43A047;      /* Green 600 */\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #388E3C;      /* Green 700 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2E7D32;      /* Green 800 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BDBDBD;\n"
"    color: #666666;\n"
"}\n"
"")
        self.saveButton.setObjectName("saveButton")
        self.leftButtonFrame.addWidget(self.saveButton)
        self.clearButton = QtWidgets.QPushButton(self.leftMenu)
        self.clearButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"    color: #FFFFFF;\n"
"\n"
"    background-color: #E53935;      /* Red 600 */\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D32F2F;      /* Red 700 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C62828;      /* Red 800 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BDBDBD;\n"
"    color: #666666;\n"
"}\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.leftButtonFrame.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.leftButtonFrame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.mainMenu = QtWidgets.QFrame(self.centralwidget)
        self.mainMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainMenu.setObjectName("mainMenu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainMenu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.mainMenu)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;          /* medium-bold */\n"
"    color: #FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.plant = QtWidgets.QPushButton(self.mainMenu)
        self.plant.setMinimumSize(QtCore.QSize(233, 233))
        self.plant.setMaximumSize(QtCore.QSize(233, 233))
        self.plant.setStyleSheet("QPushButton {\n"
"    image: url(:/desain/plant.png);\n"
"    background-color: #FFFFFF;      \n"
"    border: 3px solid #E60000;       /* merah tebal */\n"
"    border-radius: 18px;             /* rounded bentuk kotak lembut */\n"
"    padding: 10px;\n"
"    \n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #E60000;\n"
"\n"
"    /* Shadow halus agar efek floating */\n"
"    \n"
"}\n"
"\n"
"/* Hover: sedikit gelap */\n"
"QPushButton:hover {\n"
"    background-color: #FFF5F5;\n"
"    border-color: #CC0000;\n"
"}\n"
"\n"
"/* Pressed: lebih gelap & sedikit shrink effect */\n"
"QPushButton:pressed {\n"
"    background-color: #FFE5E5;\n"
"    border-color: #B80000;\n"
"    padding-top: 12px;        /* efek tombol ditekan */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.plant.setText("")
        self.plant.setObjectName("plant")
        self.gridLayout_3.addWidget(self.plant, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 6, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 3, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.mainMenu)
        self.label_7.setStyleSheet("QLabel {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;          /* medium-bold */\n"
"    color: #FFFFFF;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.mainMenu)
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;          /* medium-bold */\n"
"    color: #FFFFFF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.mainMenu)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;          /* medium-bold */\n"
"    color: #FFFFFF;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.plantwobsv = QtWidgets.QPushButton(self.mainMenu)
        self.plantwobsv.setMinimumSize(QtCore.QSize(233, 233))
        self.plantwobsv.setMaximumSize(QtCore.QSize(233, 233))
        self.plantwobsv.setStyleSheet("QPushButton {\n"
"    image: url(:/desain/plantobserver.png);\n"
"    background-color: #FFFFFF;      \n"
"    border: 3px solid #E60000;       /* merah tebal */\n"
"    border-radius: 18px;             /* rounded bentuk kotak lembut */\n"
"    padding: 10px;\n"
"    \n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #E60000;\n"
"\n"
"    /* Shadow halus agar efek floating */\n"
"    \n"
"}\n"
"\n"
"/* Hover: sedikit gelap */\n"
"QPushButton:hover {\n"
"    background-color: #FFF5F5;\n"
"    border-color: #CC0000;\n"
"}\n"
"\n"
"/* Pressed: lebih gelap & sedikit shrink effect */\n"
"QPushButton:pressed {\n"
"    background-color: #FFE5E5;\n"
"    border-color: #B80000;\n"
"    padding-top: 12px;        /* efek tombol ditekan */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.plantwobsv.setText("")
        self.plantwobsv.setObjectName("plantwobsv")
        self.gridLayout_3.addWidget(self.plantwobsv, 2, 4, 1, 1)
        self.plantwctrl = QtWidgets.QPushButton(self.mainMenu)
        self.plantwctrl.setMinimumSize(QtCore.QSize(233, 233))
        self.plantwctrl.setMaximumSize(QtCore.QSize(233, 233))
        self.plantwctrl.setStyleSheet("QPushButton {\n"
"    image: url(:/desain/plantcontroller.png);\n"
"    background-color: #FFFFFF;      \n"
"    border: 3px solid #E60000;       /* merah tebal */\n"
"    border-radius: 18px;             /* rounded bentuk kotak lembut */\n"
"    padding: 10px;\n"
"    \n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #E60000;\n"
"\n"
"    /* Shadow halus agar efek floating */\n"
"    \n"
"}\n"
"\n"
"/* Hover: sedikit gelap */\n"
"QPushButton:hover {\n"
"    background-color: #FFF5F5;\n"
"    border-color: #CC0000;\n"
"}\n"
"\n"
"/* Pressed: lebih gelap & sedikit shrink effect */\n"
"QPushButton:pressed {\n"
"    background-color: #FFE5E5;\n"
"    border-color: #B80000;\n"
"    padding-top: 12px;        /* efek tombol ditekan */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.plantwctrl.setText("")
        self.plantwctrl.setObjectName("plantwctrl")
        self.gridLayout_3.addWidget(self.plantwctrl, 5, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 3, 1, 1)
        self.plantwobsvwctrl = QtWidgets.QPushButton(self.mainMenu)
        self.plantwobsvwctrl.setMinimumSize(QtCore.QSize(233, 233))
        self.plantwobsvwctrl.setMaximumSize(QtCore.QSize(233, 233))
        self.plantwobsvwctrl.setStyleSheet("QPushButton {\n"
"    image: url(:/desain/plantcontrolobserve.png);\n"
"    background-color: #FFFFFF;      \n"
"    border: 3px solid #E60000;       /* merah tebal */\n"
"    border-radius: 18px;             /* rounded bentuk kotak lembut */\n"
"    padding: 10px;\n"
"    \n"
"    font-family: \"Poppins\";\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    color: #E60000;\n"
"\n"
"    /* Shadow halus agar efek floating */\n"
"    \n"
"}\n"
"\n"
"/* Hover: sedikit gelap */\n"
"QPushButton:hover {\n"
"    background-color: #FFF5F5;\n"
"    border-color: #CC0000;\n"
"}\n"
"\n"
"/* Pressed: lebih gelap & sedikit shrink effect */\n"
"QPushButton:pressed {\n"
"    background-color: #FFE5E5;\n"
"    border-color: #B80000;\n"
"    padding-top: 12px;        /* efek tombol ditekan */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.plantwobsvwctrl.setText("")
        self.plantwobsvwctrl.setObjectName("plantwobsvwctrl")
        self.gridLayout_3.addWidget(self.plantwobsvwctrl, 5, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 7, 3, 1, 1)
        self.horizontalLayout.addWidget(self.mainMenu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.leftMotorPG.setText(_translate("MainWindow", "<"))
        self.rightMotorPG.setText(_translate("MainWindow", ">"))
        self.leftDamperPG.setText(_translate("MainWindow", "<"))
        self.rightDamperPG.setText(_translate("MainWindow", ">"))
        self.leftBuckPG.setText(_translate("MainWindow", "<"))
        self.rightBuckPG.setText(_translate("MainWindow", ">"))
        self.rLabel.setText(_translate("MainWindow", "R = "))
        self.lLabel.setText(_translate("MainWindow", "L = "))
        self.nLabel.setText(_translate("MainWindow", "N = "))
        self.matrixBLabel.setText(_translate("MainWindow", "Bd = "))
        self.matrixALabel.setText(_translate("MainWindow", "Ad = "))
        self.label_2.setText(_translate("MainWindow", "Setpoint ="))
        self.unitLabel.setText(_translate("MainWindow", "unit"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.label_4.setText(_translate("MainWindow", "Plot Plant Response"))
        self.label_7.setText(_translate("MainWindow", "Plot Controller with Observer"))
        self.label_5.setText(_translate("MainWindow", "Plot Real and Observed States"))
        self.label_6.setText(_translate("MainWindow", "Plot State-Feedback"))
