# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul8/ui_8/problemMotor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 633)
        MainWindow.setMinimumSize(QtCore.QSize(820, 600))
        MainWindow.setMaximumSize(QtCore.QSize(820, 633))
        MainWindow.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(750, 50))
        self.label.setMaximumSize(QtCore.QSize(750, 50))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Poppins\";\n"
"    font-size: 35pt;\n"
"    font-weight: 600;          /* medium-bold */\n"
"    color: #FFFFFF;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(800, 550))
        self.frame.setMaximumSize(QtCore.QSize(800, 550))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #FFFFFF;   /* putih */\n"
"    border-radius: 16px;         /* atur besar lengkung sudut */\n"
"    border: none;                /* kalau mau tanpa garis pinggir */\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.problemMotor = QtWidgets.QLabel(self.frame)
        self.problemMotor.setObjectName("problemMotor")
        self.gridLayout_2.addWidget(self.problemMotor, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Problem"))
        self.problemMotor.setText(_translate("MainWindow", "TextLabel"))
