# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul6/UI6/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Navbar = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.Navbar.sizePolicy().hasHeightForWidth())
        self.Navbar.setSizePolicy(sizePolicy)
        self.Navbar.setMinimumSize(QtCore.QSize(0, 75))
        self.Navbar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 5px;")
        self.Navbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Navbar.setObjectName("Navbar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Navbar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setStyleSheet("image: url(:/Asset/Asset/Header.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.Navbar)
        self.frame_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_2.setStyleSheet("image: url(:/Asset/Asset/SSM.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_7.addWidget(self.Navbar)
        self.Bawah = QtWidgets.QFrame(self.frame)
        self.Bawah.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bawah.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bawah.setObjectName("Bawah")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Bawah)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Kiri = QtWidgets.QFrame(self.Bawah)
        self.Kiri.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Kiri.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Kiri.setObjectName("Kiri")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Kiri)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Monitor = QtWidgets.QFrame(self.Kiri)
        self.Monitor.setStyleSheet("")
        self.Monitor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Monitor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Monitor.setObjectName("Monitor")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Monitor)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: \"SF Pro Display\"; ")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RangkaianA = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RangkaianA.sizePolicy().hasHeightForWidth())
        self.RangkaianA.setSizePolicy(sizePolicy)
        self.RangkaianA.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RangkaianA.setStyleSheet("QPushButton {\n"
"         background-color: rgb(255, 255, 255, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(214, 0, 0);\n"
"        font-size: 40px;\n"
"        padding:0px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255, 225);\n"
"}")
        self.RangkaianA.setObjectName("RangkaianA")
        self.verticalLayout_8.addWidget(self.RangkaianA)
        self.RangkaianB = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RangkaianB.sizePolicy().hasHeightForWidth())
        self.RangkaianB.setSizePolicy(sizePolicy)
        self.RangkaianB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RangkaianB.setStyleSheet("QPushButton {\n"
"         background-color: rgb(255, 255, 255, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(214, 0, 0);\n"
"        font-size: 40px;\n"
"        padding:0px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255, 225);\n"
"}")
        self.RangkaianB.setObjectName("RangkaianB")
        self.verticalLayout_8.addWidget(self.RangkaianB)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.Meter = QtWidgets.QFrame(self.Monitor)
        self.Meter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Meter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Meter.setObjectName("Meter")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Meter)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Ampmeter = QtWidgets.QFrame(self.Meter)
        self.Ampmeter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Ampmeter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Ampmeter.setObjectName("Ampmeter")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Ampmeter)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.NoAmpmeter = QtWidgets.QLCDNumber(self.Ampmeter)
        self.NoAmpmeter.setStyleSheet("color: rgb(255, 255, 255);")
        self.NoAmpmeter.setObjectName("NoAmpmeter")
        self.horizontalLayout_8.addWidget(self.NoAmpmeter)
        self.label_2 = QtWidgets.QLabel(self.Ampmeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(56, 0))
        self.label_2.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.Ampmeter)
        self.Voltmeter = QtWidgets.QFrame(self.Meter)
        self.Voltmeter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Voltmeter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Voltmeter.setObjectName("Voltmeter")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Voltmeter)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.NoVoltmeter = QtWidgets.QLCDNumber(self.Voltmeter)
        self.NoVoltmeter.setStyleSheet("color: rgb(255, 255, 255);")
        self.NoVoltmeter.setObjectName("NoVoltmeter")
        self.horizontalLayout_7.addWidget(self.NoVoltmeter)
        self.label = QtWidgets.QLabel(self.Voltmeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(56, 0))
        self.label.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.Voltmeter)
        self.horizontalLayout_6.addWidget(self.Meter)
        self.verticalLayout_2.addWidget(self.Monitor)
        self.StateEquation = QtWidgets.QGroupBox(self.Kiri)
        self.StateEquation.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: \"SF Pro Display\"; ")
        self.StateEquation.setObjectName("StateEquation")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.StateEquation)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.MatrixDot = QtWidgets.QFrame(self.StateEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatrixDot.sizePolicy().hasHeightForWidth())
        self.MatrixDot.setSizePolicy(sizePolicy)
        self.MatrixDot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixDot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixDot.setObjectName("MatrixDot")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.MatrixDot)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.frame_57 = QtWidgets.QFrame(self.MatrixDot)
        self.frame_57.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_57.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_57.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_28.addWidget(self.frame_57)
        self.frame_58 = QtWidgets.QFrame(self.MatrixDot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_58.sizePolicy().hasHeightForWidth())
        self.frame_58.setSizePolicy(sizePolicy)
        self.frame_58.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_58)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.DOT1 = QtWidgets.QLabel(self.frame_58)
        self.DOT1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.DOT1.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.DOT1.setAlignment(QtCore.Qt.AlignCenter)
        self.DOT1.setObjectName("DOT1")
        self.verticalLayout_16.addWidget(self.DOT1)
        self.DOT2 = QtWidgets.QLabel(self.frame_58)
        self.DOT2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.DOT2.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.DOT2.setAlignment(QtCore.Qt.AlignCenter)
        self.DOT2.setObjectName("DOT2")
        self.verticalLayout_16.addWidget(self.DOT2)
        self.DOT3 = QtWidgets.QLabel(self.frame_58)
        self.DOT3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.DOT3.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.DOT3.setAlignment(QtCore.Qt.AlignCenter)
        self.DOT3.setObjectName("DOT3")
        self.verticalLayout_16.addWidget(self.DOT3)
        self.horizontalLayout_28.addWidget(self.frame_58)
        self.frame_59 = QtWidgets.QFrame(self.MatrixDot)
        self.frame_59.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_59.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_59.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.horizontalLayout_28.addWidget(self.frame_59)
        self.horizontalLayout_30.addWidget(self.MatrixDot)
        self.label_20 = QtWidgets.QLabel(self.StateEquation)
        self.label_20.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_30.addWidget(self.label_20)
        self.MatrixA = QtWidgets.QFrame(self.StateEquation)
        self.MatrixA.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixA.setObjectName("MatrixA")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.MatrixA)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_48 = QtWidgets.QFrame(self.MatrixA)
        self.frame_48.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_48.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_48.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"\n"
"")
        self.frame_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_23.addWidget(self.frame_48)
        self.frame_49 = QtWidgets.QFrame(self.MatrixA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_49.sizePolicy().hasHeightForWidth())
        self.frame_49.setSizePolicy(sizePolicy)
        self.frame_49.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        self.frame_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_50)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.A1 = QtWidgets.QLineEdit(self.frame_50)
        self.A1.setMinimumSize(QtCore.QSize(0, 0))
        self.A1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A1.setAlignment(QtCore.Qt.AlignCenter)
        self.A1.setObjectName("A1")
        self.horizontalLayout_24.addWidget(self.A1)
        self.A2 = QtWidgets.QLineEdit(self.frame_50)
        self.A2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A2.setAlignment(QtCore.Qt.AlignCenter)
        self.A2.setObjectName("A2")
        self.horizontalLayout_24.addWidget(self.A2)
        self.A3 = QtWidgets.QLineEdit(self.frame_50)
        self.A3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A3.setAlignment(QtCore.Qt.AlignCenter)
        self.A3.setObjectName("A3")
        self.horizontalLayout_24.addWidget(self.A3)
        self.verticalLayout_14.addWidget(self.frame_50)
        self.frame_51 = QtWidgets.QFrame(self.frame_49)
        self.frame_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_51)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.A4 = QtWidgets.QLineEdit(self.frame_51)
        self.A4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A4.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A4.setAlignment(QtCore.Qt.AlignCenter)
        self.A4.setObjectName("A4")
        self.horizontalLayout_25.addWidget(self.A4)
        self.A5 = QtWidgets.QLineEdit(self.frame_51)
        self.A5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A5.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A5.setAlignment(QtCore.Qt.AlignCenter)
        self.A5.setObjectName("A5")
        self.horizontalLayout_25.addWidget(self.A5)
        self.A6 = QtWidgets.QLineEdit(self.frame_51)
        self.A6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A6.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A6.setAlignment(QtCore.Qt.AlignCenter)
        self.A6.setObjectName("A6")
        self.horizontalLayout_25.addWidget(self.A6)
        self.verticalLayout_14.addWidget(self.frame_51)
        self.frame_52 = QtWidgets.QFrame(self.frame_49)
        self.frame_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.A7 = QtWidgets.QLineEdit(self.frame_52)
        self.A7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A7.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A7.setAlignment(QtCore.Qt.AlignCenter)
        self.A7.setObjectName("A7")
        self.horizontalLayout_26.addWidget(self.A7)
        self.A8 = QtWidgets.QLineEdit(self.frame_52)
        self.A8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A8.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A8.setAlignment(QtCore.Qt.AlignCenter)
        self.A8.setObjectName("A8")
        self.horizontalLayout_26.addWidget(self.A8)
        self.A9 = QtWidgets.QLineEdit(self.frame_52)
        self.A9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.A9.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.A9.setAlignment(QtCore.Qt.AlignCenter)
        self.A9.setObjectName("A9")
        self.horizontalLayout_26.addWidget(self.A9)
        self.verticalLayout_14.addWidget(self.frame_52)
        self.horizontalLayout_23.addWidget(self.frame_49)
        self.frame_53 = QtWidgets.QFrame(self.MatrixA)
        self.frame_53.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_53.setMaximumSize(QtCore.QSize(15, 160))
        self.frame_53.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_23.addWidget(self.frame_53)
        self.horizontalLayout_30.addWidget(self.MatrixA)
        self.StateVariabel = QtWidgets.QFrame(self.StateEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StateVariabel.sizePolicy().hasHeightForWidth())
        self.StateVariabel.setSizePolicy(sizePolicy)
        self.StateVariabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StateVariabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StateVariabel.setObjectName("StateVariabel")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.StateVariabel)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.frame_54 = QtWidgets.QFrame(self.StateVariabel)
        self.frame_54.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_54.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_54.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_27.addWidget(self.frame_54)
        self.frame_55 = QtWidgets.QFrame(self.StateVariabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_55.sizePolicy().hasHeightForWidth())
        self.frame_55.setSizePolicy(sizePolicy)
        self.frame_55.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_55)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.State1 = QtWidgets.QLabel(self.frame_55)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.State1.sizePolicy().hasHeightForWidth())
        self.State1.setSizePolicy(sizePolicy)
        self.State1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.State1.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.State1.setAlignment(QtCore.Qt.AlignCenter)
        self.State1.setObjectName("State1")
        self.verticalLayout_15.addWidget(self.State1)
        self.State2 = QtWidgets.QLabel(self.frame_55)
        self.State2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.State2.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.State2.setAlignment(QtCore.Qt.AlignCenter)
        self.State2.setObjectName("State2")
        self.verticalLayout_15.addWidget(self.State2)
        self.State3 = QtWidgets.QLabel(self.frame_55)
        self.State3.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.State3.setAlignment(QtCore.Qt.AlignCenter)
        self.State3.setObjectName("State3")
        self.verticalLayout_15.addWidget(self.State3)
        self.horizontalLayout_27.addWidget(self.frame_55)
        self.frame_56 = QtWidgets.QFrame(self.StateVariabel)
        self.frame_56.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_56.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_56.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_27.addWidget(self.frame_56)
        self.horizontalLayout_30.addWidget(self.StateVariabel)
        self.label_24 = QtWidgets.QLabel(self.StateEquation)
        self.label_24.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_30.addWidget(self.label_24)
        self.MatrixB = QtWidgets.QFrame(self.StateEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatrixB.sizePolicy().hasHeightForWidth())
        self.MatrixB.setSizePolicy(sizePolicy)
        self.MatrixB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixB.setObjectName("MatrixB")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.MatrixB)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_45 = QtWidgets.QFrame(self.MatrixB)
        self.frame_45.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_45.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_45.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_22.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.MatrixB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_46.sizePolicy().hasHeightForWidth())
        self.frame_46.setSizePolicy(sizePolicy)
        self.frame_46.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.B1 = QtWidgets.QLineEdit(self.frame_46)
        self.B1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.B1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.B1.setAlignment(QtCore.Qt.AlignCenter)
        self.B1.setObjectName("B1")
        self.verticalLayout_13.addWidget(self.B1)
        self.B2 = QtWidgets.QLineEdit(self.frame_46)
        self.B2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.B2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.B2.setAlignment(QtCore.Qt.AlignCenter)
        self.B2.setObjectName("B2")
        self.verticalLayout_13.addWidget(self.B2)
        self.B3 = QtWidgets.QLineEdit(self.frame_46)
        self.B3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.B3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.B3.setAlignment(QtCore.Qt.AlignCenter)
        self.B3.setObjectName("B3")
        self.verticalLayout_13.addWidget(self.B3)
        self.horizontalLayout_22.addWidget(self.frame_46)
        self.frame_47 = QtWidgets.QFrame(self.MatrixB)
        self.frame_47.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_47.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_47.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_22.addWidget(self.frame_47)
        self.horizontalLayout_30.addWidget(self.MatrixB)
        self.InputVariabel = QtWidgets.QFrame(self.StateEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputVariabel.sizePolicy().hasHeightForWidth())
        self.InputVariabel.setSizePolicy(sizePolicy)
        self.InputVariabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.InputVariabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputVariabel.setObjectName("InputVariabel")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.InputVariabel)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_60 = QtWidgets.QFrame(self.InputVariabel)
        self.frame_60.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_60.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_60.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.horizontalLayout_29.addWidget(self.frame_60)
        self.label_25 = QtWidgets.QLabel(self.InputVariabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_25.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_29.addWidget(self.label_25)
        self.frame_61 = QtWidgets.QFrame(self.InputVariabel)
        self.frame_61.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_61.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_61.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_61.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.horizontalLayout_29.addWidget(self.frame_61)
        self.horizontalLayout_30.addWidget(self.InputVariabel)
        self.verticalLayout_2.addWidget(self.StateEquation)
        self.OutputEquation = QtWidgets.QGroupBox(self.Kiri)
        self.OutputEquation.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: \"SF Pro Display\"; ")
        self.OutputEquation.setObjectName("OutputEquation")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.OutputEquation)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Output = QtWidgets.QFrame(self.OutputEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Output.sizePolicy().hasHeightForWidth())
        self.Output.setSizePolicy(sizePolicy)
        self.Output.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Output.setObjectName("Output")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.Output)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.frame_76 = QtWidgets.QFrame(self.Output)
        self.frame_76.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_76.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_76.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_76.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_76.setObjectName("frame_76")
        self.horizontalLayout_38.addWidget(self.frame_76)
        self.frame_77 = QtWidgets.QFrame(self.Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_77.sizePolicy().hasHeightForWidth())
        self.frame_77.setSizePolicy(sizePolicy)
        self.frame_77.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_77.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_77.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_77.setObjectName("frame_77")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_77)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.Yvar = QtWidgets.QLabel(self.frame_77)
        self.Yvar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Yvar.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.Yvar.setAlignment(QtCore.Qt.AlignCenter)
        self.Yvar.setObjectName("Yvar")
        self.verticalLayout_20.addWidget(self.Yvar)
        self.horizontalLayout_38.addWidget(self.frame_77)
        self.frame_78 = QtWidgets.QFrame(self.Output)
        self.frame_78.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_78.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_78.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_78.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_78.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_78.setObjectName("frame_78")
        self.horizontalLayout_38.addWidget(self.frame_78)
        self.horizontalLayout_5.addWidget(self.Output)
        self.label_26 = QtWidgets.QLabel(self.OutputEquation)
        self.label_26.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.MatrixC = QtWidgets.QFrame(self.OutputEquation)
        self.MatrixC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixC.setObjectName("MatrixC")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.MatrixC)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_64 = QtWidgets.QFrame(self.MatrixC)
        self.frame_64.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_64)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MatrixA_2 = QtWidgets.QFrame(self.frame_64)
        self.MatrixA_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixA_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixA_2.setObjectName("MatrixA_2")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.MatrixA_2)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_62 = QtWidgets.QFrame(self.MatrixA_2)
        self.frame_62.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_62.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_62.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"\n"
"")
        self.frame_62.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.horizontalLayout_32.addWidget(self.frame_62)
        self.frame_63 = QtWidgets.QFrame(self.MatrixA_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_63.sizePolicy().hasHeightForWidth())
        self.frame_63.setSizePolicy(sizePolicy)
        self.frame_63.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_63.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_63)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_65 = QtWidgets.QFrame(self.frame_63)
        self.frame_65.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_65)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.C1 = QtWidgets.QLineEdit(self.frame_65)
        self.C1.setMinimumSize(QtCore.QSize(0, 0))
        self.C1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C1.setAlignment(QtCore.Qt.AlignCenter)
        self.C1.setObjectName("C1")
        self.horizontalLayout_33.addWidget(self.C1)
        self.C2 = QtWidgets.QLineEdit(self.frame_65)
        self.C2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C2.setAlignment(QtCore.Qt.AlignCenter)
        self.C2.setObjectName("C2")
        self.horizontalLayout_33.addWidget(self.C2)
        self.C3 = QtWidgets.QLineEdit(self.frame_65)
        self.C3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C3.setAlignment(QtCore.Qt.AlignCenter)
        self.C3.setObjectName("C3")
        self.horizontalLayout_33.addWidget(self.C3)
        self.verticalLayout_17.addWidget(self.frame_65)
        self.frame_66 = QtWidgets.QFrame(self.frame_63)
        self.frame_66.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_66.setObjectName("frame_66")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_66)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.C4 = QtWidgets.QLineEdit(self.frame_66)
        self.C4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C4.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C4.setAlignment(QtCore.Qt.AlignCenter)
        self.C4.setObjectName("C4")
        self.horizontalLayout_34.addWidget(self.C4)
        self.C5 = QtWidgets.QLineEdit(self.frame_66)
        self.C5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C5.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C5.setAlignment(QtCore.Qt.AlignCenter)
        self.C5.setObjectName("C5")
        self.horizontalLayout_34.addWidget(self.C5)
        self.C6 = QtWidgets.QLineEdit(self.frame_66)
        self.C6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C6.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C6.setAlignment(QtCore.Qt.AlignCenter)
        self.C6.setObjectName("C6")
        self.horizontalLayout_34.addWidget(self.C6)
        self.verticalLayout_17.addWidget(self.frame_66)
        self.frame_67 = QtWidgets.QFrame(self.frame_63)
        self.frame_67.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_67)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.C7 = QtWidgets.QLineEdit(self.frame_67)
        self.C7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C7.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C7.setAlignment(QtCore.Qt.AlignCenter)
        self.C7.setObjectName("C7")
        self.horizontalLayout_39.addWidget(self.C7)
        self.C8 = QtWidgets.QLineEdit(self.frame_67)
        self.C8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C8.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C8.setAlignment(QtCore.Qt.AlignCenter)
        self.C8.setObjectName("C8")
        self.horizontalLayout_39.addWidget(self.C8)
        self.C9 = QtWidgets.QLineEdit(self.frame_67)
        self.C9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.C9.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.C9.setAlignment(QtCore.Qt.AlignCenter)
        self.C9.setObjectName("C9")
        self.horizontalLayout_39.addWidget(self.C9)
        self.verticalLayout_17.addWidget(self.frame_67)
        self.horizontalLayout_32.addWidget(self.frame_63)
        self.frame_79 = QtWidgets.QFrame(self.MatrixA_2)
        self.frame_79.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_79.setMaximumSize(QtCore.QSize(15, 160))
        self.frame_79.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_79.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_79.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_79.setObjectName("frame_79")
        self.horizontalLayout_32.addWidget(self.frame_79)
        self.verticalLayout_4.addWidget(self.MatrixA_2)
        self.horizontalLayout_31.addWidget(self.frame_64)
        self.horizontalLayout_5.addWidget(self.MatrixC)
        self.StateVariabel_2 = QtWidgets.QFrame(self.OutputEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StateVariabel_2.sizePolicy().hasHeightForWidth())
        self.StateVariabel_2.setSizePolicy(sizePolicy)
        self.StateVariabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StateVariabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StateVariabel_2.setObjectName("StateVariabel_2")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.StateVariabel_2)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.frame_73 = QtWidgets.QFrame(self.StateVariabel_2)
        self.frame_73.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_73.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_73.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_73.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.horizontalLayout_37.addWidget(self.frame_73)
        self.frame_74 = QtWidgets.QFrame(self.StateVariabel_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_74.sizePolicy().hasHeightForWidth())
        self.frame_74.setSizePolicy(sizePolicy)
        self.frame_74.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_74.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_74.setObjectName("frame_74")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_74)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.OutputState1 = QtWidgets.QLabel(self.frame_74)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputState1.sizePolicy().hasHeightForWidth())
        self.OutputState1.setSizePolicy(sizePolicy)
        self.OutputState1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.OutputState1.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.OutputState1.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputState1.setObjectName("OutputState1")
        self.verticalLayout_19.addWidget(self.OutputState1)
        self.OutputState2 = QtWidgets.QLabel(self.frame_74)
        self.OutputState2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.OutputState2.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.OutputState2.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputState2.setObjectName("OutputState2")
        self.verticalLayout_19.addWidget(self.OutputState2)
        self.OutputState3 = QtWidgets.QLabel(self.frame_74)
        self.OutputState3.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.OutputState3.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputState3.setObjectName("OutputState3")
        self.verticalLayout_19.addWidget(self.OutputState3)
        self.horizontalLayout_37.addWidget(self.frame_74)
        self.frame_75 = QtWidgets.QFrame(self.StateVariabel_2)
        self.frame_75.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_75.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_75.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_75.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_75.setObjectName("frame_75")
        self.horizontalLayout_37.addWidget(self.frame_75)
        self.horizontalLayout_5.addWidget(self.StateVariabel_2)
        self.label_28 = QtWidgets.QLabel(self.OutputEquation)
        self.label_28.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_5.addWidget(self.label_28)
        self.MatrixD = QtWidgets.QFrame(self.OutputEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatrixD.sizePolicy().hasHeightForWidth())
        self.MatrixD.setSizePolicy(sizePolicy)
        self.MatrixD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MatrixD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MatrixD.setObjectName("MatrixD")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.MatrixD)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_71 = QtWidgets.QFrame(self.MatrixD)
        self.frame_71.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_71.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_71.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_71.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_71.setObjectName("frame_71")
        self.horizontalLayout_10.addWidget(self.frame_71)
        self.frame_70 = QtWidgets.QFrame(self.MatrixD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_70.sizePolicy().hasHeightForWidth())
        self.frame_70.setSizePolicy(sizePolicy)
        self.frame_70.setStyleSheet("border: 2px;\n"
"border-color:  rgb(255, 255, 255);")
        self.frame_70.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_70.setObjectName("frame_70")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_70)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.D1 = QtWidgets.QLineEdit(self.frame_70)
        self.D1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.D1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.D1.setAlignment(QtCore.Qt.AlignCenter)
        self.D1.setObjectName("D1")
        self.verticalLayout_18.addWidget(self.D1)
        self.D2 = QtWidgets.QLineEdit(self.frame_70)
        self.D2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.D2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.D2.setAlignment(QtCore.Qt.AlignCenter)
        self.D2.setObjectName("D2")
        self.verticalLayout_18.addWidget(self.D2)
        self.D3 = QtWidgets.QLineEdit(self.frame_70)
        self.D3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.D3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"font-size: 10px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.D3.setAlignment(QtCore.Qt.AlignCenter)
        self.D3.setObjectName("D3")
        self.verticalLayout_18.addWidget(self.D3)
        self.horizontalLayout_10.addWidget(self.frame_70)
        self.frame_72 = QtWidgets.QFrame(self.MatrixD)
        self.frame_72.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_72.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_72.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_72.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.horizontalLayout_10.addWidget(self.frame_72)
        self.horizontalLayout_5.addWidget(self.MatrixD)
        self.InputVariabel_2 = QtWidgets.QFrame(self.OutputEquation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputVariabel_2.sizePolicy().hasHeightForWidth())
        self.InputVariabel_2.setSizePolicy(sizePolicy)
        self.InputVariabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.InputVariabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputVariabel_2.setObjectName("InputVariabel_2")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.InputVariabel_2)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.frame_68 = QtWidgets.QFrame(self.InputVariabel_2)
        self.frame_68.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_68.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_68.setStyleSheet("border-top: 3px solid white;\n"
"border-left: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_68.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.horizontalLayout_35.addWidget(self.frame_68)
        self.label_27 = QtWidgets.QLabel(self.InputVariabel_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_27.setStyleSheet("border-radius : 2px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"padding:3px;\n"
"font-family: \"SF Pro Display\"; \n"
"        font-weight: bold; \n"
"        font-style: normal;")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_35.addWidget(self.label_27)
        self.frame_69 = QtWidgets.QFrame(self.InputVariabel_2)
        self.frame_69.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_69.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_69.setStyleSheet("border-top: 3px solid white;\n"
"border-right: 3px solid white;\n"
"border-bottom: 3px solid white;\n"
"")
        self.frame_69.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.horizontalLayout_35.addWidget(self.frame_69)
        self.horizontalLayout_5.addWidget(self.InputVariabel_2)
        self.verticalLayout_2.addWidget(self.OutputEquation)
        self.horizontalLayout.addWidget(self.Kiri)
        self.Kanan = QtWidgets.QFrame(self.Bawah)
        self.Kanan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Kanan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Kanan.setObjectName("Kanan")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Kanan)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.Kanan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PlotFrame = QtWidgets.QWidget(self.frame_5)
        self.PlotFrame.setObjectName("PlotFrame")
        self.verticalLayout_6.addWidget(self.PlotFrame)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.Kanan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: \"SF Pro Display\"; ")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Chart = QtWidgets.QPushButton(self.groupBox)
        self.Chart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chart.setStyleSheet("QPushButton {\n"
"        image: url(:/Asset/Asset/Chart kosong.png);\n"
"         background-color: rgb(255, 255, 255, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(214, 0, 0);\n"
"        font-size: 40px;\n"
"        padding:0px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Chart isi.png);\n"
"    background-color: rgb(255, 255, 255, 225);\n"
"}")
        self.Chart.setText("")
        self.Chart.setObjectName("Chart")
        self.horizontalLayout_4.addWidget(self.Chart)
        self.CSV = QtWidgets.QPushButton(self.groupBox)
        self.CSV.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CSV.setStyleSheet("QPushButton {\n"
"        image: url(:/Asset/Asset/CSV1.png);\n"
"         background-color: rgb(255, 255, 255, 255);\n"
"        border-color: rgb(255, 255, 255);\n"
"        border-radius : 2px;\n"
"        color: rgb(214, 0, 0);\n"
"        font-size: 40px;\n"
"        padding:0px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/CSV2.png);\n"
"    background-color: rgb(255, 255, 255, 225);\n"
"}")
        self.CSV.setText("")
        self.CSV.setObjectName("CSV")
        self.horizontalLayout_4.addWidget(self.CSV)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.Kanan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Run = QtWidgets.QPushButton(self.frame_7)
        self.Run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Run.setStyleSheet("QPushButton {\n"
"        image: url(:/Asset/Asset/Run1.png);\n"
"         background-color: rgb(0, 255, 0, 255);\n"
"        border-color: rgb(0, 255, 0);\n"
"        border-radius : 2px;\n"
"        color: rgb(255, 255, 255);\n"
"        font-size: 30px;\n"
"        padding:7px;\n"
"        font-family: \"SF Pro Display\"; \n"
"            font-weight: bold; \n"
"            font-style: normal;\n"
"\n"
"}\n"
"\n"
"/* Saat mouse hover */\n"
"QPushButton:hover {\n"
"    image: url(:/Asset/Asset/Run2.png);\n"
"    background-color: rgb(0, 255, 0, 225);\n"
"}")
        self.Run.setText("")
        self.Run.setObjectName("Run")
        self.horizontalLayout_9.addWidget(self.Run)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.Kanan)
        self.verticalLayout_7.addWidget(self.Bawah)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Rangkaian"))
        self.RangkaianA.setText(_translate("MainWindow", "A"))
        self.RangkaianB.setText(_translate("MainWindow", "B"))
        self.label_2.setText(_translate("MainWindow", "A"))
        self.label.setText(_translate("MainWindow", "V"))
        self.StateEquation.setTitle(_translate("MainWindow", "State Eq."))
        self.DOT1.setText(_translate("MainWindow", "dIL"))
        self.DOT2.setText(_translate("MainWindow", "dVC1"))
        self.DOT3.setText(_translate("MainWindow", "dVC2"))
        self.label_20.setText(_translate("MainWindow", "="))
        self.State1.setText(_translate("MainWindow", "IL"))
        self.State2.setText(_translate("MainWindow", "VC1"))
        self.State3.setText(_translate("MainWindow", "VC2"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "Vin"))
        self.OutputEquation.setTitle(_translate("MainWindow", "Output Eq."))
        self.Yvar.setText(_translate("MainWindow", "Y"))
        self.label_26.setText(_translate("MainWindow", "="))
        self.OutputState1.setText(_translate("MainWindow", "IL"))
        self.OutputState2.setText(_translate("MainWindow", "VC1"))
        self.OutputState3.setText(_translate("MainWindow", "VC2"))
        self.label_28.setText(_translate("MainWindow", "+"))
        self.label_27.setText(_translate("MainWindow", "Vin"))
        self.groupBox.setTitle(_translate("MainWindow", "Save"))
