# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/Amatrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(220, 220)
        MainWindow.setStyleSheet("QWidget {\n"
"    border-image: url(:/newPrefix/Amatrix2.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName("centralwidget")
        self.a11 = QtWidgets.QLabel(self.centralwidget)
        self.a11.setGeometry(QtCore.QRect(40, 36, 48, 48))
        self.a11.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a11.setAlignment(QtCore.Qt.AlignCenter)
        self.a11.setObjectName("a11")
        self.a12 = QtWidgets.QLabel(self.centralwidget)
        self.a12.setGeometry(QtCore.QRect(88, 36, 48, 48))
        self.a12.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a12.setAlignment(QtCore.Qt.AlignCenter)
        self.a12.setObjectName("a12")
        self.a13 = QtWidgets.QLabel(self.centralwidget)
        self.a13.setGeometry(QtCore.QRect(136, 36, 48, 48))
        self.a13.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a13.setAlignment(QtCore.Qt.AlignCenter)
        self.a13.setObjectName("a13")
        self.a21 = QtWidgets.QLabel(self.centralwidget)
        self.a21.setGeometry(QtCore.QRect(40, 84, 48, 48))
        self.a21.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a21.setAlignment(QtCore.Qt.AlignCenter)
        self.a21.setObjectName("a21")
        self.a23 = QtWidgets.QLabel(self.centralwidget)
        self.a23.setGeometry(QtCore.QRect(136, 84, 48, 48))
        self.a23.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a23.setAlignment(QtCore.Qt.AlignCenter)
        self.a23.setObjectName("a23")
        self.a22 = QtWidgets.QLabel(self.centralwidget)
        self.a22.setGeometry(QtCore.QRect(88, 84, 48, 48))
        self.a22.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a22.setAlignment(QtCore.Qt.AlignCenter)
        self.a22.setObjectName("a22")
        self.a31 = QtWidgets.QLabel(self.centralwidget)
        self.a31.setGeometry(QtCore.QRect(40, 132, 48, 48))
        self.a31.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a31.setAlignment(QtCore.Qt.AlignCenter)
        self.a31.setObjectName("a31")
        self.a33 = QtWidgets.QLabel(self.centralwidget)
        self.a33.setGeometry(QtCore.QRect(136, 132, 48, 48))
        self.a33.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a33.setAlignment(QtCore.Qt.AlignCenter)
        self.a33.setObjectName("a33")
        self.a32 = QtWidgets.QLabel(self.centralwidget)
        self.a32.setGeometry(QtCore.QRect(88, 132, 48, 48))
        self.a32.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.a32.setAlignment(QtCore.Qt.AlignCenter)
        self.a32.setObjectName("a32")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.a11.setText(_translate("MainWindow", "1"))
        self.a12.setText(_translate("MainWindow", "1"))
        self.a13.setText(_translate("MainWindow", "1"))
        self.a21.setText(_translate("MainWindow", "1"))
        self.a23.setText(_translate("MainWindow", "1"))
        self.a22.setText(_translate("MainWindow", "1"))
        self.a31.setText(_translate("MainWindow", "1"))
        self.a33.setText(_translate("MainWindow", "1"))
        self.a32.setText(_translate("MainWindow", "1"))
