# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/Bmatrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 220)
        MainWindow.setStyleSheet("border-image: url(:/newPrefix/Bmatrix2.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b11 = QtWidgets.QLabel(self.centralwidget)
        self.b11.setGeometry(QtCore.QRect(87, 40, 48, 48))
        self.b11.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.b11.setAlignment(QtCore.Qt.AlignCenter)
        self.b11.setObjectName("b11")
        self.b21 = QtWidgets.QLabel(self.centralwidget)
        self.b21.setGeometry(QtCore.QRect(87, 88, 48, 48))
        self.b21.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.b21.setAlignment(QtCore.Qt.AlignCenter)
        self.b21.setObjectName("b21")
        self.b31 = QtWidgets.QLabel(self.centralwidget)
        self.b31.setGeometry(QtCore.QRect(87, 136, 48, 48))
        self.b31.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.b31.setAlignment(QtCore.Qt.AlignCenter)
        self.b31.setObjectName("b31")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b11.setText(_translate("MainWindow", "1"))
        self.b21.setText(_translate("MainWindow", "1"))
        self.b31.setText(_translate("MainWindow", "1"))
