# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/Controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 207)
        MainWindow.setStyleSheet("background-color: rgb(206, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 45, 41, 37))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.updateR = QtWidgets.QPushButton(self.frame)
        self.updateR.setGeometry(QtCore.QRect(20, 130, 501, 32))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.updateR.setFont(font)
        self.updateR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateR.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 30px;\n"
"    color: rgb(214, 0, 0);\n"
"    font-size: 15px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\"; \n"
"    font-weight: normal; \n"
"    font-style: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200); \n"
"}\n"
"")
        self.updateR.setObjectName("updateR")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(100, 20, 421, 87))
        self.frame_2.setStyleSheet("image: url(:/newPrefix/Rcontroller.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.r11 = QtWidgets.QLineEdit(self.frame_2)
        self.r11.setGeometry(QtCore.QRect(30, 25, 100, 36))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r11.setFont(font)
        self.r11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding: 7px 0px 7px 5px; /* top, right, bottom, left */\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.r11.setText("")
        self.r11.setAlignment(QtCore.Qt.AlignCenter)
        self.r11.setObjectName("r11")
        self.r12 = QtWidgets.QLineEdit(self.frame_2)
        self.r12.setGeometry(QtCore.QRect(150, 25, 110, 36))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r12.setFont(font)
        self.r12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding: 7px 0px 7px 5px; /* top, right, bottom, left */\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.r12.setText("")
        self.r12.setAlignment(QtCore.Qt.AlignCenter)
        self.r12.setObjectName("r12")
        self.r13 = QtWidgets.QLineEdit(self.frame_2)
        self.r13.setGeometry(QtCore.QRect(280, 25, 110, 36))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r13.setFont(font)
        self.r13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding: 7px 0px 7px 5px; /* top, right, bottom, left */\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.r13.setText("")
        self.r13.setAlignment(QtCore.Qt.AlignCenter)
        self.r13.setObjectName("r13")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "R ="))
        self.updateR.setText(_translate("MainWindow", "Update"))
