# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/Cmatrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 220)
        MainWindow.setStyleSheet("border-image: url(:/newPrefix/Cmatrix2.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.c13 = QtWidgets.QLabel(self.centralwidget)
        self.c13.setGeometry(QtCore.QRect(136, 87, 48, 48))
        self.c13.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.c13.setAlignment(QtCore.Qt.AlignCenter)
        self.c13.setObjectName("c13")
        self.c12 = QtWidgets.QLabel(self.centralwidget)
        self.c12.setGeometry(QtCore.QRect(88, 87, 48, 48))
        self.c12.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.c12.setAlignment(QtCore.Qt.AlignCenter)
        self.c12.setObjectName("c12")
        self.c11 = QtWidgets.QLabel(self.centralwidget)
        self.c11.setGeometry(QtCore.QRect(40, 87, 48, 48))
        self.c11.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-image: none;\n"
"}\n"
"")
        self.c11.setAlignment(QtCore.Qt.AlignCenter)
        self.c11.setObjectName("c11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.c13.setText(_translate("MainWindow", "1"))
        self.c12.setText(_translate("MainWindow", "1"))
        self.c11.setText(_translate("MainWindow", "1"))
