# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("border-image: url(:/newPrefix/mainbg.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.runBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runBtn.setGeometry(QtCore.QRect(1093, 550, 181, 71))
        self.runBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.runBtn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/newPrefix/runsim.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/runsim1.png);\n"
"}")
        self.runBtn.setText("")
        self.runBtn.setObjectName("runBtn")
        self.scopebtn = QtWidgets.QPushButton(self.centralwidget)
        self.scopebtn.setGeometry(QtCore.QRect(1195, 190, 67, 82))
        self.scopebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scopebtn.setMouseTracking(True)
        self.scopebtn.setStyleSheet("QPushButton {\n"
"     border-image: url(:/newPrefix/scope.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/scope1.png);\n"
"}")
        self.scopebtn.setText("")
        self.scopebtn.setObjectName("scopebtn")
        self.Cbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Cbtn.setGeometry(QtCore.QRect(925, 198, 100, 66))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Cbtn.setFont(font)
        self.Cbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cbtn.setStyleSheet("QPushButton { \n"
"    border-image: url(:/newPrefix/Cmatrix.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/Cmatrix1.png);\n"
"}")
        self.Cbtn.setText("")
        self.Cbtn.setObjectName("Cbtn")
        self.Abtn = QtWidgets.QPushButton(self.centralwidget)
        self.Abtn.setGeometry(QtCore.QRect(734, 304, 100, 66))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Abtn.setFont(font)
        self.Abtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Abtn.setStyleSheet("QPushButton { \n"
"    border-image: url(:/newPrefix/Amatrix.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/Amatrix1.png);\n"
"}")
        self.Abtn.setText("")
        self.Abtn.setObjectName("Abtn")
        self.Dbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Dbtn.setGeometry(QtCore.QRect(734, 411, 100, 66))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Dbtn.setFont(font)
        self.Dbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dbtn.setStyleSheet("QPushButton { \n"
"    border-image: url(:/newPrefix/Dmatrix.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/Dmatrix1.png);\n"
"}")
        self.Dbtn.setText("")
        self.Dbtn.setObjectName("Dbtn")
        self.Rbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Rbtn.setGeometry(QtCore.QRect(733, 519, 100, 66))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Rbtn.setFont(font)
        self.Rbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Rbtn.setStyleSheet("QPushButton { \n"
"    border-image: url(:/newPrefix/controller.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/controller1.png);\n"
"}")
        self.Rbtn.setText("")
        self.Rbtn.setObjectName("Rbtn")
        self.Bbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Bbtn.setGeometry(QtCore.QRect(480, 198, 100, 66))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Bbtn.setFont(font)
        self.Bbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bbtn.setStyleSheet("QPushButton { \n"
"    border-image: url(:/newPrefix/Bmatrix.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/newPrefix/Bmatrix1.png);\n"
"}")
        self.Bbtn.setText("")
        self.Bbtn.setObjectName("Bbtn")
        self.Nbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Nbtn.setGeometry(QtCore.QRect(200, 200, 66, 67))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(40)
        self.Nbtn.setFont(font)
        self.Nbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nbtn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/newPrefix/pregain.png);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      border-image: url(:/newPrefix/pregain1.png);\n"
"}\n"
"")
        self.Nbtn.setText("")
        self.Nbtn.setObjectName("Nbtn")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(70, 119, 171, 61))
        self.frame_2.setStyleSheet("border-image : none;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 151, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-image: none;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.frame_2)
        self.label_1.setGeometry(QtCore.QRect(10, 5, 161, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-image: none;")
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Settling Time: "))
        self.label_1.setText(_translate("MainWindow", "Overshoot:"))
