# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul7/UI/PreGain.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(275, 165)
        MainWindow.setStyleSheet("background-color: rgb(206, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.N = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.N.setFont(font)
        self.N.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(143, 0, 0);\n"
"border-bottom: 2px solid rgba(255, 255, 255, 100);\n"
"padding: 7px 0px 7px 5px; /* top, right, bottom, left */\n"
"font-size: 15px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;")
        self.N.setText("")
        self.N.setObjectName("N")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.N)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.updateN = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.updateN.setFont(font)
        self.updateN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateN.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 30px;\n"
"    color: rgb(214, 0, 0);\n"
"    font-size: 15px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\"; \n"
"    font-weight: normal; \n"
"    font-style: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200); \n"
"}\n"
"")
        self.updateN.setObjectName("updateN")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.updateN)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "N ="))
        self.updateN.setText(_translate("MainWindow", "Update"))
