# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul910/ui_910/calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 315)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: rgb(226, 0, 0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done.sizePolicy().hasHeightForWidth())
        self.done.setSizePolicy(sizePolicy)
        self.done.setMaximumSize(QtCore.QSize(150, 16777215))
        self.done.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 255, 0);   /* bright green */\n"
"    border: 2px solid rgb(85, 255, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);           /* white text */\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darker shade */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 150, 0); /* darker green */\n"
"    border-color: rgb(50, 150, 0);\n"
"    color: rgb(255, 255, 255); /* keep white text */\n"
"}\n"
"")
        self.done.setObjectName("done")
        self.horizontalLayout_2.addWidget(self.done)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.min = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min.sizePolicy().hasHeightForWidth())
        self.min.setSizePolicy(sizePolicy)
        self.min.setMinimumSize(QtCore.QSize(0, 0))
        self.min.setMaximumSize(QtCore.QSize(50, 50))
        self.min.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(214, 0, 0);\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: button itself becomes yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darken */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.min.setObjectName("min")
        self.horizontalLayout_3.addWidget(self.min)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pls = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pls.sizePolicy().hasHeightForWidth())
        self.pls.setSizePolicy(sizePolicy)
        self.pls.setMaximumSize(QtCore.QSize(50, 50))
        self.pls.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(214, 0, 0);\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: button itself becomes yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darken */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.pls.setObjectName("pls")
        self.horizontalLayout_3.addWidget(self.pls)
        spacerItem3 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.pulse = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse.sizePolicy().hasHeightForWidth())
        self.pulse.setSizePolicy(sizePolicy)
        self.pulse.setMaximumSize(QtCore.QSize(300, 100))
        self.pulse.setStyleSheet("QLCDNumber{\n"
"    color: red;           \n"
"    background: white;    \n"
"    border: 5px solid gray;\n"
"}")
        self.pulse.setObjectName("pulse")
        self.gridLayout.addWidget(self.pulse, 2, 1, 1, 1)
        self.rotation = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotation.sizePolicy().hasHeightForWidth())
        self.rotation.setSizePolicy(sizePolicy)
        self.rotation.setMaximumSize(QtCore.QSize(300, 100))
        self.rotation.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 64px;\n"
"    border: 5px solid gray;\n"
"}")
        self.rotation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rotation.setObjectName("rotation")
        self.gridLayout.addWidget(self.rotation, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font-size: 32px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Number of Pulses"))
        self.done.setText(_translate("MainWindow", "Done"))
        self.min.setText(_translate("MainWindow", "-"))
        self.pls.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "Number of Rotation"))
        self.rotation.setPlaceholderText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "="))
