# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul910/ui_910/clc.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 935)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: rgb(226, 0, 0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.clcgraph = QtWidgets.QFrame(self.frame_12)
        self.clcgraph.setStyleSheet("QWidget#clcgraph{\n"
"    background-color: rgb(209, 209, 209);\n"
"}")
        self.clcgraph.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.clcgraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clcgraph.setObjectName("clcgraph")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.clcgraph)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.popup = QtWidgets.QPushButton(self.clcgraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.popup.sizePolicy().hasHeightForWidth())
        self.popup.setSizePolicy(sizePolicy)
        self.popup.setMinimumSize(QtCore.QSize(50, 50))
        self.popup.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/popupicon.png);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/popupiconclk.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/popupiconclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.popup.setText("")
        self.popup.setObjectName("popup")
        self.gridLayout_3.addWidget(self.popup, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.clcgraph)
        self.controlgraph = QtWidgets.QFrame(self.frame_12)
        self.controlgraph.setStyleSheet("QWidget#controlgraph{\n"
"    background-color: rgb(209, 209, 209);\n"
"}")
        self.controlgraph.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.controlgraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlgraph.setObjectName("controlgraph")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.controlgraph)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(846, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 303, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 1, 1, 1, 1)
        self.popup_2 = QtWidgets.QPushButton(self.controlgraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.popup_2.sizePolicy().hasHeightForWidth())
        self.popup_2.setSizePolicy(sizePolicy)
        self.popup_2.setMinimumSize(QtCore.QSize(50, 50))
        self.popup_2.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/popupicon.png);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/popupiconclk.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/popupiconclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.popup_2.setText("")
        self.popup_2.setObjectName("popup_2")
        self.gridLayout_5.addWidget(self.popup_2, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.controlgraph)
        self.horizontalLayout.addWidget(self.frame_12)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.targetRPM = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetRPM.sizePolicy().hasHeightForWidth())
        self.targetRPM.setSizePolicy(sizePolicy)
        self.targetRPM.setMinimumSize(QtCore.QSize(250, 0))
        self.targetRPM.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    border: 5px solid gray;\n"
"}")
        self.targetRPM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetRPM.setObjectName("targetRPM")
        self.verticalLayout_5.addWidget(self.targetRPM)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.k1 = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k1.sizePolicy().hasHeightForWidth())
        self.k1.setSizePolicy(sizePolicy)
        self.k1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    border: 5px solid gray;\n"
"}")
        self.k1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k1.setObjectName("k1")
        self.gridLayout.addWidget(self.k1, 0, 1, 1, 1)
        self.k2 = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k2.sizePolicy().hasHeightForWidth())
        self.k2.setSizePolicy(sizePolicy)
        self.k2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    border: 5px solid gray;\n"
"}")
        self.k2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k2.setObjectName("k2")
        self.gridLayout.addWidget(self.k2, 1, 1, 1, 1)
        self.k3 = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k3.sizePolicy().hasHeightForWidth())
        self.k3.setSizePolicy(sizePolicy)
        self.k3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    border: 5px solid gray;\n"
"}")
        self.k3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k3.setObjectName("k3")
        self.gridLayout.addWidget(self.k3, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._100ms = QtWidgets.QRadioButton(self.frame_8)
        self._100ms.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self._100ms.setObjectName("_100ms")
        self.gridLayout_2.addWidget(self._100ms, 2, 0, 1, 1)
        self._10ms = QtWidgets.QRadioButton(self.frame_8)
        self._10ms.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self._10ms.setObjectName("_10ms")
        self.gridLayout_2.addWidget(self._10ms, 0, 0, 1, 1)
        self._500ms = QtWidgets.QRadioButton(self.frame_8)
        self._500ms.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self._500ms.setObjectName("_500ms")
        self.gridLayout_2.addWidget(self._500ms, 3, 0, 1, 1)
        self._50ms = QtWidgets.QRadioButton(self.frame_8)
        self._50ms.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self._50ms.setObjectName("_50ms")
        self.gridLayout_2.addWidget(self._50ms, 1, 0, 1, 1)
        self._1000ms = QtWidgets.QRadioButton(self.frame_8)
        self._1000ms.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self._1000ms.setObjectName("_1000ms")
        self.gridLayout_2.addWidget(self._1000ms, 4, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.os = QtWidgets.QLabel(self.frame_11)
        self.os.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.os.setAlignment(QtCore.Qt.AlignCenter)
        self.os.setObjectName("os")
        self.gridLayout_4.addWidget(self.os, 3, 1, 1, 1)
        self.Ts = QtWidgets.QLabel(self.frame_11)
        self.Ts.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.Ts.setAlignment(QtCore.Qt.AlignCenter)
        self.Ts.setObjectName("Ts")
        self.gridLayout_4.addWidget(self.Ts, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.Tr = QtWidgets.QLabel(self.frame_11)
        self.Tr.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.Tr.setAlignment(QtCore.Qt.AlignCenter)
        self.Tr.setObjectName("Tr")
        self.gridLayout_4.addWidget(self.Tr, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.Tp = QtWidgets.QLabel(self.frame_11)
        self.Tp.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.Tp.setAlignment(QtCore.Qt.AlignCenter)
        self.Tp.setObjectName("Tp")
        self.gridLayout_4.addWidget(self.Tp, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(593, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.start = QtWidgets.QPushButton(self.frame_4)
        self.start.setMinimumSize(QtCore.QSize(150, 0))
        self.start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 255, 0);   /* bright green */\n"
"    border: 2px solid rgb(85, 255, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);           /* white text */\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darker shade */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 150, 0); /* darker green */\n"
"    border-color: rgb(50, 150, 0);\n"
"    color: rgb(255, 255, 255); /* keep white text */\n"
"}\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_2.addWidget(self.start)
        spacerItem5 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.analyze = QtWidgets.QPushButton(self.frame_4)
        self.analyze.setMinimumSize(QtCore.QSize(150, 0))
        self.analyze.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);   /* bright green */\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(226, 0, 0);           /* white text */\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darker shade */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 150, 0); /* darker green */\n"
"    border-color: rgb(50, 150, 0);\n"
"    color: rgb(255, 255, 255); /* keep white text */\n"
"}\n"
"")
        self.analyze.setObjectName("analyze")
        self.horizontalLayout_2.addWidget(self.analyze)
        spacerItem7 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Target RPM:"))
        self.label.setText(_translate("MainWindow", "Control Parameter"))
        self.label_4.setText(_translate("MainWindow", "K3                :"))
        self.label_2.setText(_translate("MainWindow", "K1                :"))
        self.label_3.setText(_translate("MainWindow", "K2                :"))
        self.label_8.setText(_translate("MainWindow", "Sampling Rate"))
        self._100ms.setText(_translate("MainWindow", "100 ms"))
        self._10ms.setText(_translate("MainWindow", "10 ms"))
        self._500ms.setText(_translate("MainWindow", "500 ms"))
        self._50ms.setText(_translate("MainWindow", "50 ms"))
        self._1000ms.setText(_translate("MainWindow", "1000 ms"))
        self.label_9.setText(_translate("MainWindow", "Transient Response"))
        self.os.setText(_translate("MainWindow", "--"))
        self.Ts.setText(_translate("MainWindow", "--"))
        self.label_15.setText(_translate("MainWindow", "%OS             :"))
        self.Tr.setText(_translate("MainWindow", "--"))
        self.label_13.setText(_translate("MainWindow", "Tr                  :"))
        self.label_10.setText(_translate("MainWindow", "Ts                  :"))
        self.label_6.setText(_translate("MainWindow", "Tp                  :"))
        self.Tp.setText(_translate("MainWindow", "--"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.analyze.setText(_translate("MainWindow", "Analyze"))
