# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul910/ui_910/lrc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 274)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: rgb(226, 0, 0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.minLinDisp = QtWidgets.QLabel(self.frame_3)
        self.minLinDisp.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.minLinDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.minLinDisp.setObjectName("minLinDisp")
        self.horizontalLayout_2.addWidget(self.minLinDisp)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.maxLinDisp = QtWidgets.QLabel(self.frame_3)
        self.maxLinDisp.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.maxLinDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.maxLinDisp.setObjectName("maxLinDisp")
        self.horizontalLayout_2.addWidget(self.maxLinDisp)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.MinRPMDisp = QtWidgets.QLabel(self.frame_3)
        self.MinRPMDisp.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.MinRPMDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.MinRPMDisp.setObjectName("MinRPMDisp")
        self.horizontalLayout_2.addWidget(self.MinRPMDisp)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.MaxRPMDisp = QtWidgets.QLabel(self.frame_3)
        self.MaxRPMDisp.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.MaxRPMDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxRPMDisp.setObjectName("MaxRPMDisp")
        self.horizontalLayout_2.addWidget(self.MaxRPMDisp)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.minLinPWM = QtWidgets.QLineEdit(self.frame)
        self.minLinPWM.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 32px;\n"
"    border: 5px solid gray;\n"
"}")
        self.minLinPWM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minLinPWM.setObjectName("minLinPWM")
        self.gridLayout.addWidget(self.minLinPWM, 0, 1, 1, 1)
        self.minLinRPM = QtWidgets.QLineEdit(self.frame)
        self.minLinRPM.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 32px;\n"
"    border: 5px solid gray;\n"
"}")
        self.minLinRPM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minLinRPM.setObjectName("minLinRPM")
        self.gridLayout.addWidget(self.minLinRPM, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.maxLinRPM = QtWidgets.QLineEdit(self.frame)
        self.maxLinRPM.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 32px;\n"
"    border: 5px solid gray;\n"
"}")
        self.maxLinRPM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxLinRPM.setObjectName("maxLinRPM")
        self.gridLayout.addWidget(self.maxLinRPM, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.maxLinPWM = QtWidgets.QLineEdit(self.frame)
        self.maxLinPWM.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 32px;\n"
"    border: 5px solid gray;\n"
"}")
        self.maxLinPWM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxLinPWM.setObjectName("maxLinPWM")
        self.gridLayout.addWidget(self.maxLinPWM, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("font-size: 24px;\n"
"font-family: \"SF Pro Display\"; \n"
"    font-weight: bold; \n"
"    font-style: normal;\n"
"color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.done = QtWidgets.QPushButton(self.frame_2)
        self.done.setMinimumSize(QtCore.QSize(150, 0))
        self.done.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 255, 0);   /* bright green */\n"
"    border: 2px solid rgb(85, 255, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);           /* white text */\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darker shade */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 150, 0); /* darker green */\n"
"    border-color: rgb(50, 150, 0);\n"
"    color: rgb(255, 255, 255); /* keep white text */\n"
"}\n"
"")
        self.done.setObjectName("done")
        self.horizontalLayout.addWidget(self.done)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "MinLinPWM   :"))
        self.minLinDisp.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "MaxLinPWM  :"))
        self.maxLinDisp.setText(_translate("MainWindow", "--"))
        self.label_7.setText(_translate("MainWindow", "MinLinRPM   :"))
        self.MinRPMDisp.setText(_translate("MainWindow", "--"))
        self.label_9.setText(_translate("MainWindow", "MaxLinRPM  :"))
        self.MaxRPMDisp.setText(_translate("MainWindow", "--"))
        self.label_5.setText(_translate("MainWindow", "| MinLinRPM :"))
        self.label.setText(_translate("MainWindow", "MinLinPWM :"))
        self.label_6.setText(_translate("MainWindow", "| MaxLinRPM :"))
        self.label_2.setText(_translate("MainWindow", "MaxLinPWM :"))
        self.done.setText(_translate("MainWindow", "Done"))
