# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul910/ui_910/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    qproperty-autoFillBackground: true; /* ensure it paints its own background */\n"
"    border-image: url(:/main/bgMain.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 159, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ppr = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppr.sizePolicy().hasHeightForWidth())
        self.ppr.setSizePolicy(sizePolicy)
        self.ppr.setMinimumSize(QtCore.QSize(100, 0))
        self.ppr.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.ppr.setAlignment(QtCore.Qt.AlignCenter)
        self.ppr.setObjectName("ppr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ppr)
        self.maxRPM = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxRPM.sizePolicy().hasHeightForWidth())
        self.maxRPM.setSizePolicy(sizePolicy)
        self.maxRPM.setMinimumSize(QtCore.QSize(100, 0))
        self.maxRPM.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.maxRPM.setAlignment(QtCore.Qt.AlignCenter)
        self.maxRPM.setObjectName("maxRPM")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxRPM)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(283, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 419, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.olc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.olc.sizePolicy().hasHeightForWidth())
        self.olc.setSizePolicy(sizePolicy)
        self.olc.setMinimumSize(QtCore.QSize(135, 135))
        self.olc.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/olc.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/olc.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/olclck.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.olc.setText("")
        self.olc.setObjectName("olc")
        self.horizontalLayout_5.addWidget(self.olc)
        spacerItem5 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 3, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 7, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusIndicator = QtWidgets.QLabel(self.centralwidget)
        self.statusIndicator.setMinimumSize(QtCore.QSize(30, 30))
        self.statusIndicator.setMaximumSize(QtCore.QSize(24, 24))
        self.statusIndicator.setStyleSheet("QLabel#statusIndicator{\n"
"    border-image: url(:/main/noSignal.png);\n"
"}\n"
"\n"
"QLabel#statusIndicator[status=\"green\"] {\n"
"    border-image: url(:/main/goodSignal.png);\n"
"}\n"
"\n"
"QLabel#statusIndicator[status=\"red\"] {\n"
"    border-image: url(:/main/noSignal.png); /* or a red icon */\n"
"}")
        self.statusIndicator.setText("")
        self.statusIndicator.setObjectName("statusIndicator")
        self.horizontalLayout_4.addWidget(self.statusIndicator)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 6, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clc.sizePolicy().hasHeightForWidth())
        self.clc.setSizePolicy(sizePolicy)
        self.clc.setMinimumSize(QtCore.QSize(135, 135))
        self.clc.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/clc.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/clc.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/clcclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.clc.setText("")
        self.clc.setObjectName("clc")
        self.horizontalLayout_2.addWidget(self.clc)
        spacerItem8 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem9, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.log = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        self.log.setMinimumSize(QtCore.QSize(135, 135))
        self.log.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/pwmspeed.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/pwmspeed.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/pwmclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.log.setText("")
        self.log.setObjectName("log")
        self.horizontalLayout_6.addWidget(self.log)
        spacerItem10 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 6, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lrc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lrc.sizePolicy().hasHeightForWidth())
        self.lrc.setSizePolicy(sizePolicy)
        self.lrc.setMinimumSize(QtCore.QSize(135, 135))
        self.lrc.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/linear.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/linear.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/linearclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.lrc.setText("")
        self.lrc.setObjectName("lrc")
        self.horizontalLayout_8.addWidget(self.lrc)
        spacerItem11 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 6, 5, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sa = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sa.sizePolicy().hasHeightForWidth())
        self.sa.setSizePolicy(sizePolicy)
        self.sa.setMinimumSize(QtCore.QSize(135, 135))
        self.sa.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/submit.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/submit.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/submitclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.sa.setText("")
        self.sa.setObjectName("sa")
        self.horizontalLayout_7.addWidget(self.sa)
        spacerItem12 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 5, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 3, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 3, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.encoder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encoder.sizePolicy().hasHeightForWidth())
        self.encoder.setSizePolicy(sizePolicy)
        self.encoder.setMinimumSize(QtCore.QSize(135, 135))
        self.encoder.setStyleSheet("QPushButton {\n"
"    border-image: url(:/main/calibrate.png);\n"
"    border: 2px solid transparent;  /* Invisible border to maintain size */\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/calibrate.png);\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/calclk.png);\n"
"    background-color: none;\n"
"    border-radius: 8px;  /* Rounded corners */\n"
"}")
        self.encoder.setText("")
        self.encoder.setObjectName("encoder")
        self.horizontalLayout_9.addWidget(self.encoder)
        spacerItem15 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 6, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 8, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem17, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 16pt;\n"
"color: rgb(255, 255, 255);")
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 7, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 5, 3, 1, 1)
        self.ports = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ports.sizePolicy().hasHeightForWidth())
        self.ports.setSizePolicy(sizePolicy)
        self.ports.setMinimumSize(QtCore.QSize(0, 0))
        self.ports.setCurrentText("")
        self.ports.setObjectName("ports")
        self.gridLayout_3.addWidget(self.ports, 1, 5, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PPR             :"))
        self.label_2.setText(_translate("MainWindow", "max RPM  :"))
        self.ppr.setText(_translate("MainWindow", "--"))
        self.maxRPM.setText(_translate("MainWindow", "--"))
        self.label_6.setText(_translate("MainWindow", "Open Loop Control"))
        self.label_10.setText(_translate("MainWindow", "Linear Region Setup"))
        self.label_7.setText(_translate("MainWindow", "Submit     Answers"))
        self.label_8.setText(_translate("MainWindow", "Encoder Calibration"))
        self.label_5.setText(_translate("MainWindow", "Closed Loop Control"))
        self.label_9.setText(_translate("MainWindow", "PWM to Speed Logging"))
