# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul910/ui_910/sa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 434)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: rgb(226, 0, 0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.L_fopdt = QtWidgets.QLineEdit(self.centralwidget)
        self.L_fopdt.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.L_fopdt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_fopdt.setObjectName("L_fopdt")
        self.gridLayout.addWidget(self.L_fopdt, 8, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.K1 = QtWidgets.QLineEdit(self.centralwidget)
        self.K1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.K1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.K1.setObjectName("K1")
        self.gridLayout.addWidget(self.K1, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 3, 1, 1)
        self.K2 = QtWidgets.QLineEdit(self.centralwidget)
        self.K2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.K2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.K2.setObjectName("K2")
        self.gridLayout.addWidget(self.K2, 6, 5, 1, 1)
        self.K_fopdt = QtWidgets.QLineEdit(self.centralwidget)
        self.K_fopdt.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.K_fopdt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.K_fopdt.setObjectName("K_fopdt")
        self.gridLayout.addWidget(self.K_fopdt, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 18pt;\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 2)
        self.K3 = QtWidgets.QLineEdit(self.centralwidget)
        self.K3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.K3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.K3.setObjectName("K3")
        self.gridLayout.addWidget(self.K3, 8, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 4, 1, 1)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit.sizePolicy().hasHeightForWidth())
        self.submit.setSizePolicy(sizePolicy)
        self.submit.setMinimumSize(QtCore.QSize(150, 0))
        self.submit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 255, 0);   /* bright green */\n"
"    border: 2px solid rgb(85, 255, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);           /* white text */\n"
"    font-size: 30px;\n"
"    padding: 7px;\n"
"    font-family: \"SF Pro Display\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Hover effect: yellow */\n"
"QPushButton:hover {\n"
"    border-color: rgb(255, 230, 50);\n"
"}\n"
"\n"
"/* Pressed effect: darker shade */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 150, 0); /* darker green */\n"
"    border-color: rgb(50, 150, 0);\n"
"    color: rgb(255, 255, 255); /* keep white text */\n"
"}\n"
"")
        self.submit.setObjectName("submit")
        self.gridLayout.addWidget(self.submit, 10, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font-family: \"Iceland\";\n"
"font-size: 14pt;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        self.tau_fopdt = QtWidgets.QLineEdit(self.centralwidget)
        self.tau_fopdt.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border: 5px solid gray;\n"
"}")
        self.tau_fopdt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tau_fopdt.setObjectName("tau_fopdt")
        self.gridLayout.addWidget(self.tau_fopdt, 6, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 11, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "K             :"))
        self.label_3.setText(_translate("MainWindow", "L              :"))
        self.label_7.setText(_translate("MainWindow", "DC Motor \n"
" Modelling"))
        self.label_2.setText(_translate("MainWindow", "𝜏              :"))
        self.label_4.setText(_translate("MainWindow", "K1            :"))
        self.label_8.setText(_translate("MainWindow", "DC Motor \n"
" Controller Design"))
        self.label_6.setText(_translate("MainWindow", "K3            :"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.label_5.setText(_translate("MainWindow", "K2            :"))
