# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/Modul4/ui/MainModul4.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: rgb(8, 29, 56);\n"
"        color: rgb(255,255,255);\n"
"        font-size: 10pt;\n"
"    }\n"
"    QGroupBox {\n"
"        border: 1px solid rgb(197,218,247);\n"
"        margin-top: 20px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 10px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit {\n"
"        border: 1px solid rgb(197,218,247);\n"
"        padding: 4px;\n"
"        background-color: rgb(25,15,12);\n"
"        color: white;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: rgb(197,218,247);\n"
"        color: black;\n"
"        padding: 6px;\n"
"        border-radius: 4px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(255,128,128);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(255,0,0);\n"
"    }\n"
"    QLabel {\n"
"        color: white;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.topBar = QtWidgets.QHBoxLayout()
        self.topBar.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.topBar.setObjectName("topBar")
        self.logoTopLeft = QtWidgets.QLabel(self.centralwidget)
        self.logoTopLeft.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoTopLeft.sizePolicy().hasHeightForWidth())
        self.logoTopLeft.setSizePolicy(sizePolicy)
        self.logoTopLeft.setMinimumSize(QtCore.QSize(100, 50))
        self.logoTopLeft.setStyleSheet("")
        self.logoTopLeft.setText("")
        self.logoTopLeft.setPixmap(QtGui.QPixmap(":/assets/assets/Header.png"))
        self.logoTopLeft.setScaledContents(True)
        self.logoTopLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.logoTopLeft.setWordWrap(False)
        self.logoTopLeft.setObjectName("logoTopLeft")
        self.topBar.addWidget(self.logoTopLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topBar.addItem(spacerItem)
        self.mainLayout.addLayout(self.topBar)
        self.groupTF = QtWidgets.QGroupBox(self.centralwidget)
        self.groupTF.setObjectName("groupTF")
        self.gridLayoutTF = QtWidgets.QGridLayout(self.groupTF)
        self.gridLayoutTF.setObjectName("gridLayoutTF")
        self.den_s1 = QtWidgets.QLineEdit(self.groupTF)
        self.den_s1.setObjectName("den_s1")
        self.gridLayoutTF.addWidget(self.den_s1, 1, 3, 1, 1)
        self.num_s1 = QtWidgets.QLineEdit(self.groupTF)
        self.num_s1.setObjectName("num_s1")
        self.gridLayoutTF.addWidget(self.num_s1, 0, 3, 1, 1)
        self.labelNum = QtWidgets.QLabel(self.groupTF)
        self.labelNum.setObjectName("labelNum")
        self.gridLayoutTF.addWidget(self.labelNum, 0, 0, 1, 1)
        self.num_s0 = QtWidgets.QLineEdit(self.groupTF)
        self.num_s0.setObjectName("num_s0")
        self.gridLayoutTF.addWidget(self.num_s0, 0, 4, 1, 1)
        self.labelDen = QtWidgets.QLabel(self.groupTF)
        self.labelDen.setObjectName("labelDen")
        self.gridLayoutTF.addWidget(self.labelDen, 1, 0, 1, 1)
        self.num_s2 = QtWidgets.QLineEdit(self.groupTF)
        self.num_s2.setObjectName("num_s2")
        self.gridLayoutTF.addWidget(self.num_s2, 0, 2, 1, 1)
        self.btnGeneratePlot = QtWidgets.QPushButton(self.groupTF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGeneratePlot.sizePolicy().hasHeightForWidth())
        self.btnGeneratePlot.setSizePolicy(sizePolicy)
        self.btnGeneratePlot.setObjectName("btnGeneratePlot")
        self.gridLayoutTF.addWidget(self.btnGeneratePlot, 0, 5, 2, 1)
        self.num_s3 = QtWidgets.QLineEdit(self.groupTF)
        self.num_s3.setObjectName("num_s3")
        self.gridLayoutTF.addWidget(self.num_s3, 0, 1, 1, 1)
        self.den_s2 = QtWidgets.QLineEdit(self.groupTF)
        self.den_s2.setObjectName("den_s2")
        self.gridLayoutTF.addWidget(self.den_s2, 1, 2, 1, 1)
        self.den_s3 = QtWidgets.QLineEdit(self.groupTF)
        self.den_s3.setObjectName("den_s3")
        self.gridLayoutTF.addWidget(self.den_s3, 1, 1, 1, 1)
        self.den_s0 = QtWidgets.QLineEdit(self.groupTF)
        self.den_s0.setObjectName("den_s0")
        self.gridLayoutTF.addWidget(self.den_s0, 1, 4, 1, 1)
        self.mainLayout.addWidget(self.groupTF)
        self.plotStatusLayout = QtWidgets.QHBoxLayout()
        self.plotStatusLayout.setObjectName("plotStatusLayout")
        self.groupPlots = QtWidgets.QGroupBox(self.centralwidget)
        self.groupPlots.setObjectName("groupPlots")
        self.horizontalLayoutPlots = QtWidgets.QHBoxLayout(self.groupPlots)
        self.horizontalLayoutPlots.setObjectName("horizontalLayoutPlots")
        self.BodePlotWidget = QtWidgets.QWidget(self.groupPlots)
        self.BodePlotWidget.setMinimumSize(QtCore.QSize(300, 250))
        self.BodePlotWidget.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.BodePlotWidget.setObjectName("BodePlotWidget")
        self.horizontalLayoutPlots.addWidget(self.BodePlotWidget)
        self.stepResponsePlotWidget = QtWidgets.QWidget(self.groupPlots)
        self.stepResponsePlotWidget.setMinimumSize(QtCore.QSize(300, 250))
        self.stepResponsePlotWidget.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.stepResponsePlotWidget.setObjectName("stepResponsePlotWidget")
        self.horizontalLayoutPlots.addWidget(self.stepResponsePlotWidget)
        self.plotStatusLayout.addWidget(self.groupPlots)
        self.groupStatus = QtWidgets.QGroupBox(self.centralwidget)
        self.groupStatus.setObjectName("groupStatus")
        self.formLayout = QtWidgets.QFormLayout(self.groupStatus)
        self.formLayout.setObjectName("formLayout")
        self.lblOvershoot = QtWidgets.QLabel(self.groupStatus)
        self.lblOvershoot.setObjectName("lblOvershoot")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblOvershoot)
        self.lblSettlingTime = QtWidgets.QLabel(self.groupStatus)
        self.lblSettlingTime.setObjectName("lblSettlingTime")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblSettlingTime)
        self.lblPeakTime = QtWidgets.QLabel(self.groupStatus)
        self.lblPeakTime.setObjectName("lblPeakTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblPeakTime)
        self.plotStatusLayout.addWidget(self.groupStatus)
        self.mainLayout.addLayout(self.plotStatusLayout)
        self.groupController = QtWidgets.QGroupBox(self.centralwidget)
        self.groupController.setObjectName("groupController")
        self.horizontalLayoutController = QtWidgets.QHBoxLayout(self.groupController)
        self.horizontalLayoutController.setObjectName("horizontalLayoutController")
        self.inputP = QtWidgets.QLineEdit(self.groupController)
        self.inputP.setObjectName("inputP")
        self.horizontalLayoutController.addWidget(self.inputP)
        self.inputI = QtWidgets.QLineEdit(self.groupController)
        self.inputI.setObjectName("inputI")
        self.horizontalLayoutController.addWidget(self.inputI)
        self.inputD = QtWidgets.QLineEdit(self.groupController)
        self.inputD.setObjectName("inputD")
        self.horizontalLayoutController.addWidget(self.inputD)
        self.inputGain = QtWidgets.QLineEdit(self.groupController)
        self.inputGain.setObjectName("inputGain")
        self.horizontalLayoutController.addWidget(self.inputGain)
        self.btnPlotWithController = QtWidgets.QPushButton(self.groupController)
        self.btnPlotWithController.setObjectName("btnPlotWithController")
        self.horizontalLayoutController.addWidget(self.btnPlotWithController)
        self.mainLayout.addWidget(self.groupController)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem1)
        self.logoBottomRight = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoBottomRight.sizePolicy().hasHeightForWidth())
        self.logoBottomRight.setSizePolicy(sizePolicy)
        self.logoBottomRight.setMinimumSize(QtCore.QSize(70, 60))
        self.logoBottomRight.setMaximumSize(QtCore.QSize(5, 200))
        self.logoBottomRight.setSizeIncrement(QtCore.QSize(0, 0))
        self.logoBottomRight.setStyleSheet("")
        self.logoBottomRight.setText("")
        self.logoBottomRight.setTextFormat(QtCore.Qt.AutoText)
        self.logoBottomRight.setPixmap(QtGui.QPixmap(":/assets/assets/Logo Controllab (2).png"))
        self.logoBottomRight.setScaledContents(True)
        self.logoBottomRight.setAlignment(QtCore.Qt.AlignCenter)
        self.logoBottomRight.setWordWrap(False)
        self.logoBottomRight.setOpenExternalLinks(False)
        self.logoBottomRight.setObjectName("logoBottomRight")
        self.bottomLayout.addWidget(self.logoBottomRight)
        self.mainLayout.addLayout(self.bottomLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Root Locus & Control System Analyzer"))
        self.groupTF.setTitle(_translate("MainWindow", "Transfer Function Input"))
        self.den_s1.setPlaceholderText(_translate("MainWindow", "s^1"))
        self.num_s1.setPlaceholderText(_translate("MainWindow", "s^1"))
        self.labelNum.setText(_translate("MainWindow", "Numerator"))
        self.num_s0.setPlaceholderText(_translate("MainWindow", "s^0"))
        self.labelDen.setText(_translate("MainWindow", "Denominator"))
        self.num_s2.setPlaceholderText(_translate("MainWindow", "s^2"))
        self.btnGeneratePlot.setText(_translate("MainWindow", "Generate Plot"))
        self.num_s3.setPlaceholderText(_translate("MainWindow", "s^3"))
        self.den_s2.setPlaceholderText(_translate("MainWindow", "s^2"))
        self.den_s3.setPlaceholderText(_translate("MainWindow", "s^3"))
        self.den_s0.setPlaceholderText(_translate("MainWindow", "s^0"))
        self.groupPlots.setTitle(_translate("MainWindow", "Plots"))
        self.BodePlotWidget.setStyleSheet(_translate("MainWindow", "border: 1px solid rgb(197,218,247);"))
        self.stepResponsePlotWidget.setStyleSheet(_translate("MainWindow", "border: 1px solid rgb(197,218,247);"))
        self.groupStatus.setTitle(_translate("MainWindow", "System Status"))
        self.lblOvershoot.setText(_translate("MainWindow", "Overshoot: -"))
        self.lblSettlingTime.setText(_translate("MainWindow", "Settling Time: -"))
        self.lblPeakTime.setText(_translate("MainWindow", "Peak Time: -"))
        self.groupController.setTitle(_translate("MainWindow", "Controller Parameters"))
        self.inputP.setPlaceholderText(_translate("MainWindow", "P"))
        self.inputI.setPlaceholderText(_translate("MainWindow", "I"))
        self.inputD.setPlaceholderText(_translate("MainWindow", "D"))
        self.inputGain.setPlaceholderText(_translate("MainWindow", "Gain"))
        self.btnPlotWithController.setText(_translate("MainWindow", "Plot Response with Controller"))
